// Knowledge checks: end-of-unit quizzes drawing from that unit's lessons.
// Same question format as lessons, but all questions (no teach steps).
// Passing requires getting a minimum number correct.

export const CHECKS = {
  check_foundations: {
    title: "Unit 1 check: Foundations",
    passMark: 6,
    practice: "Now apply it: play one scenario in the simulator. Before EVERY trade, say out loud what the entry costs you (spread + commission are simulated). Only enter if you can state, in one sentence, at what price your idea would be proven wrong.",
    questions: [
      {
        prompt: "Bid $24.90 / ask $25.10. You buy 200 shares at market then immediately sell at market. Total cost of the round trip?",
        image: "downtrend-structure",
        options: ["$4", "$40", "$400", "Nothing"],
        correctIndex: 1,
        explanation: "You pay the ask, receive the bid: $0.20 × 200 = $40 lost to the spread with zero price movement.",
      },
      {
        prompt: "Which order type guarantees your PRICE but not your FILL?",
        image: "downtrend-structure",
        options: ["Market", "Limit", "Stop", "None of them"],
        correctIndex: 1,
        explanation: "A limit order only executes at your price or better — but if the market never comes to you, it never fills.",
      },
      {
        prompt: "Price is $80. You want in only if strength is confirmed by a break above $82. Which order?",
        image: "bid-ask",
        options: ["Buy limit $82", "Buy stop $82", "Sell stop $82", "Market order now"],
        correctIndex: 1,
        explanation: "A buy stop above resistance triggers only when price trades there — entry on confirmation.",
      },
      {
        prompt: "You're long from $30, sell stop at $28. Earnings gap the open to $25. Your likely fill?",
        image: "gap-risk",
        options: ["$28 exactly", "About $25", "$30", "The order cancels"],
        correctIndex: 1,
        explanation: "Stops don't protect through gaps — they trigger and fill at the next traded price.",
      },
      {
        prompt: "Multi-step: account $5,000. You trade a thin stock with a $0.30 average spread cost, 100 shares per trade, 10 round trips a week. Roughly what % of the account goes to spread alone in a year (50 weeks)?",
        image: "trend-structure",
        options: ["3%", "10%", "30%", "300%"],
        correctIndex: 2,
        explanation: "$0.30 × 100 × 10 × 50 = $1,500 = 30% of the account. Execution cost compounds with frequency — most 'strategy' failures are really cost failures.",
      },
      {
        prompt: "TRAP: A trader brags they 'never use stop-losses, that's how the market takes your money'. The real risk of this approach?",
        image: "stop-bracket",
        options: [
          "There is none — stops are optional",
          "Losses have no defined cap; one bad trade can do damage that no win rate recovers from",
          "It only matters for big accounts",
          "Brokers require stops anyway",
        ],
        correctIndex: 1,
        explanation: "Occasional stop-hunts are the fee for the one thing that keeps you alive: a hard cap on how much any single wrong idea can cost.",
      },
      {
        prompt: "You plan: long at $45 support, wrong below $43.50, target $49. Express the whole plan in orders.",
        image: "sr-zone",
        options: [
          "Buy limit $45, sell stop $43.50, sell limit $49",
          "Buy stop $45, sell limit $43.50, sell stop $49",
          "Market buy now, no exits",
          "Buy limit $49, sell stop $45, sell limit $43.50",
        ],
        correctIndex: 0,
        explanation: "Rest the entry at the level, stop below invalidation, target above — the plan translated directly into a bracket of orders.",
      },
      {
        prompt: "Why does the same strategy often perform worse on an illiquid instrument than a liquid one?",
        image: "downtrend-structure",
        options: [
          "Illiquid instruments trend less",
          "Wider spreads and more slippage raise the cost of every entry and exit, eating the edge",
          "Charts render differently",
          "It doesn't — instruments are interchangeable",
        ],
        correctIndex: 1,
        explanation: "Edge is measured after costs. The same signals minus bigger execution tolls can flip a profitable system into a losing one.",
      },
    ],
  },

  check_reading: {
    title: "Unit 2 check: Reading the chart",
    passMark: 6,
    practice: "Now apply it: play one scenario. Before your first trade, write down (mentally or on paper) the condition — trend, range, or transition — and mark one support and one resistance zone. Only take trades that agree with your classification.",
    questions: [
      {
        prompt: "Daily candle: open $72, high $79, low $71.50, close $73. What's the honest one-line read?",
        image: "candle-anatomy",
        options: [
          "Strong bullish conviction",
          "Rally to $79 was heavily rejected — sellers drove it back near the open; caution on longs",
          "Nothing happened today",
          "Guaranteed crash tomorrow",
        ],
        correctIndex: 1,
        explanation: "A $6 upper wick against a $1 body is a rejection story: buyers tried, sellers won the day.",
      },
      {
        prompt: "Price bounces at $61.80, $62.05, $61.90 across three declines. A trader sets a limit buy at exactly $62.05 with a stop at $61.95. What's wrong?",
        image: "sr-zone",
        options: [
          "Nothing — precise is professional",
          "Both orders sit INSIDE the support zone's noise — normal zone chop will stop them out even when the level holds",
          "The stop should be above entry",
          "Limit orders can't be used at support",
        ],
        correctIndex: 1,
        explanation: "Zones are bands, not lines. Entries can be inside the zone but invalidation belongs BEYOND it (e.g. below ~$61.50), sized accordingly.",
      },
      {
        prompt: "Higher-timeframe context: weekly chart in a downtrend below broken support; 15-min chart prints a bullish hammer. Trade grade for a swing long?",
        image: "downtrend-structure",
        options: [
          "A+ — hammers are hammers",
          "Low quality — a lower-timeframe blip against dominant higher-timeframe supply",
          "Timeframes are interchangeable",
          "The weekly chart is irrelevant to swings",
        ],
        correctIndex: 1,
        explanation: "Signal weight scales with timeframe. Counter-trend lower-timeframe signals are for scalps at best, not swings against the tide.",
      },
      {
        prompt: "A breakout candle clears resistance on volume 4× average. Versus the same breakout on 0.3× volume, the high-volume version is…",
        image: "volume-conviction",
        options: [
          "Identical in meaning",
          "More trustworthy — broad participation makes reversal harder and follow-through likelier",
          "Weaker — volume is noise",
          "A guaranteed winner",
        ],
        correctIndex: 1,
        explanation: "Volume is conviction. Thin breakouts are the easiest to fade; heavy ones have real commitment behind them. Neither is certain — one is likelier.",
      },
      {
        prompt: "Six weeks of price action between $95 and $105, currently $96. Which trade fits the condition?",
        image: "range-vs-trend",
        options: [
          "Short $96 targeting $85 — momentum!",
          "Long near the $95 edge, stop below the zone, target the $105 edge",
          "Buy $100 mid-range with a $10 stop",
          "Breakout-buy $97",
        ],
        correctIndex: 1,
        explanation: "Range playbook: fade the edges with invalidation beyond the boundary. Mid-range entries and momentum plays are condition mismatches.",
      },
      {
        prompt: "An uptrend's last three pullbacks: -3%, -5%, -9%, and the latest rally barely made a new high before stalling. What's the read?",
        image: "downtrend-structure",
        options: [
          "The trend is accelerating bullishly",
          "Character change — deepening pullbacks and fading thrust are transition evidence; tighten risk on longs",
          "Pullback depth is meaningless",
          "Time to triple long exposure",
        ],
        correctIndex: 1,
        explanation: "Trends announce their aging through character: deeper retracements, weaker impulses. Not a short signal by itself — but no longer a market to treat as a clean uptrend.",
      },
      {
        prompt: "TRAP: 'The $150 level has held eight times this month, so my stop can sit right at $149.90 — it's basically a wall.' The flaw?",
        image: "downtrend-structure",
        options: [
          "None — walls are walls",
          "Rapid repeated tests EXHAUST levels, and $149.90 sits exactly in the stop-cluster below an obvious line — fragile level, worst placement",
          "Stops are never needed at walls",
          "$150 isn't a round number",
        ],
        correctIndex: 1,
        explanation: "Two lessons converge: frequent tests weaken support, and the pocket just under an obvious level is where the stops (yours included) get harvested.",
      },
      {
        prompt: "Multi-step: strong uptrend, price pulls back 4% to a zone that's produced two prior bounces, prints a long lower wick on rising volume. Assemble the read.",
        image: "wick-rejection",
        options: [
          "Random noise, no information",
          "Trend context + known demand zone + rejection wick + volume = a coherent long thesis with invalidation below the zone",
          "A short signal",
          "Wait for a 50% crash to be safe",
        ],
        correctIndex: 1,
        explanation: "This is the unit working as one skill: condition first, location second, candle-story third, volume as the conviction check — one narrative, one invalidation.",
      },
    ],
  },

  check_structure: {
    title: "Unit 3 check: Structure & zones",
    passMark: 6,
    practice: "Now apply it: play one scenario and narrate structure as bars print — label each swing HH/HL or LH/LL. Only enter after a BOS in your direction, on the pullback, with the stop beyond the zone AND the obvious liquidity pocket.",
    questions: [
      {
        prompt: "Swings: high $88 → low $82 → high $86 → low $79. Label it.",
        image: "trend-structure",
        options: [
          "Uptrend: HH + HL",
          "Downtrend: LH ($88→$86) + LL ($82→$79)",
          "A range",
          "Structure can't be labeled",
        ],
        correctIndex: 1,
        explanation: "Lower high and lower low: the downtrend skeleton. Every trade in this chart starts from that fact.",
      },
      {
        prompt: "In that downtrend, price rallies and closes decisively above the $86 lower high. What is this and what does it demand?",
        image: "downtrend-structure",
        options: [
          "BOS down — short more",
          "CHoCH — the downtrend structure just failed; stop treating rallies as automatic shorts and reassess",
          "Proof of a new uptrend, buy max size instantly",
          "Nothing notable",
        ],
        correctIndex: 1,
        explanation: "Breaking the LH against the trend is the change of character: a warning to downgrade the old bias — and confirmation (new HL then HH) is what a new long thesis waits for.",
      },
      {
        prompt: "A 200-period MA is still falling while price has already printed CHoCH, a higher low, AND a higher high. Why the disagreement?",
        image: "choch",
        options: [
          "The MA is broken",
          "Lag — long MAs average months of past prices and turn well after structure shifts; structure leads, long MAs confirm regimes",
          "Structure is always wrong",
          "MAs predict the future",
        ],
        correctIndex: 1,
        explanation: "Both tools are doing their jobs. Knowing WHAT each is late to is the skill: fresh turns belong to structure, regime confirmation to the slow average.",
      },
      {
        prompt: "RSI hits 78 during a strong uptrend, mid-move, far from any level. Per this unit, that reading alone is…",
        image: "rsi-divergence",
        options: [
          "A short signal",
          "Context only — momentum extremes mid-trend routinely persist; extremes matter at range edges or meaningful zones",
          "A buy signal by itself",
          "A system error",
        ],
        correctIndex: 1,
        explanation: "Location gives indicators meaning. The same 78 at an exhausted range high next to a fresh supply zone would be worth attention; naked and mid-trend, it's a description, not a signal.",
      },
      {
        prompt: "Price returns for the FIRST time to a zone that launched a violent 3-day rally. The zone is also a prior support flip AND sits under a swing low's stop pocket that just got swept. Grade the long setup.",
        image: "downtrend-structure",
        options: [
          "Weak — too many factors",
          "High quality: fresh zone + role-reversal level + post-sweep entry = independent evidence stacked with crisp invalidation",
          "Uninvestable",
          "Only tradeable with no stop",
        ],
        correctIndex: 1,
        explanation: "Zone freshness, S/R role logic, and the liquidity event are DIFFERENT mechanisms agreeing — the definition of real confluence, with invalidation below the sweep low.",
      },
      {
        prompt: "TRAP: price wicks $0.15 above the swing high on one candle and instantly collapses. A trader calls it 'BOS — uptrend confirmed'. The liquidity-aware read?",
        image: "wick-rejection",
        options: [
          "Correct call — any break counts",
          "More likely a sweep of buy-stops above the high; genuine breaks show ACCEPTANCE (closes and holding beyond), not one-wick pokes",
          "Swing highs cannot be swept",
          "Both reads are identical",
        ],
        correctIndex: 1,
        explanation: "The stops above an obvious high are exactly the harvest. Poke-and-reject = sweep; close-and-hold = break. Acceptance is the dividing line.",
      },
      {
        prompt: "Given sweep behavior, your long's invalidation is below a swing low at $40.00. Where does the stop go, and what else must change?",
        image: "liquidity-sweep",
        options: [
          "$39.99, maximum size",
          "Buffered beyond the pocket (e.g. ~$39.60) — and position size RECALCULATED smaller so dollar risk stays fixed",
          "No stop; sweeps make stops pointless",
          "Above $40 for safety",
        ],
        correctIndex: 1,
        explanation: "Placement escapes the harvest pocket; the wider distance is paid for with fewer shares — never with more account risk. Units 3 and 4 meet exactly here.",
      },
      {
        prompt: "A demand zone breaks on heavy volume and price ACCEPTS below it for three sessions. The zone's story now?",
        image: "volume-conviction",
        options: [
          "Still demand — buy every touch forever",
          "Failed — and likely role-flipped: expect it to act as supply/resistance on retests from below",
          "Zones never fail",
          "Redraw it lower until it works",
        ],
        correctIndex: 1,
        explanation: "Conviction breaks with acceptance end a zone's original story and often invert it. Believing the failure fast is what separates analysis from hope.",
      },
    ],
  },

  check_risk: {
    title: "Unit 4 check: Risk & process",
    passMark: 7,
    practice: "Now apply it: play one full scenario where EVERY entry is sized by the formula — pick your invalidation first, compute shares from a fixed 1% risk, and require a realistic 2:1 R:R before entering. End the session and check your achieved R against plan.",
    questions: [
      {
        prompt: "Account $8,000, risk 1% per trade. Entry $32, stop $30. Shares?",
        image: "stop-bracket",
        options: ["80", "40", "400", "250"],
        correctIndex: 1,
        explanation: "Risk $80, stop distance $2 → $80 ÷ $2 = 40 shares. Check: 40 × $2 = $80 ✓",
      },
      {
        prompt: "Same account and risk. A different setup needs a stop $4 away from a $32 entry. Shares now — and what stayed constant?",
        image: "stop-bracket",
        options: [
          "40 again",
          "20 shares — the dollar risk ($80) stayed constant while size adjusted to the wider stop",
          "80 shares to compensate",
          "The trade is impossible",
        ],
        correctIndex: 1,
        explanation: "$80 ÷ $4 = 20. Size floats, risk doesn't. This single habit removes the randomness that destroys fixed-size traders.",
      },
      {
        prompt: "System stats: 35% win rate, avg win +3R, avg loss -1R. Expectancy — and verdict?",
        image: "expectancy-bars",
        options: [
          "-0.4R, losing system",
          "+0.4R per trade — profitable despite losing 65% of the time",
          "0R, breakeven",
          "Win rate below 50% cannot profit",
        ],
        correctIndex: 1,
        explanation: "(0.35 × 3) − (0.65 × 1) = 1.05 − 0.65 = +0.4R. The whole psychology of losing streaks becomes survivable once this math is truly internalized.",
      },
      {
        prompt: "System comparison: A wins 75% with +0.4R winners; B wins 40% with +2.2R winners (both lose -1R). Which has the edge?",
        image: "expectancy-bars",
        options: [
          "A — higher win rate always wins",
          "B: A = (0.75×0.4)−(0.25×1) = +0.05R (dies to costs); B = (0.4×2.2)−(0.6×1) = +0.28R",
          "Identical",
          "Neither can be computed",
        ],
        correctIndex: 1,
        explanation: "Win rate is the most seductive and least sufficient statistic in trading. Expectancy after costs is the only scoreboard.",
      },
      {
        prompt: "You're down -2R today, feeling the pull to 'win it back'. Your plan's daily stop is -2R. The correct action and its rationale?",
        image: "downtrend-structure",
        options: [
          "One more trade — rules are guidelines",
          "Done for the day: the daily stop exists because decision quality after losses is measurably degraded — it protects the account from tilted-you",
          "Double size to recover faster",
          "Delete the daily stop rule",
        ],
        correctIndex: 1,
        explanation: "Per-trade risk guards against the market; the daily stop guards against the trader. Honoring it IS the skill being tested on days like this.",
      },
      {
        prompt: "TRAP: 'My last 6 trades all won, so this setup is basically free money — I'm risking 10% on the next one.' Identify BOTH errors.",
        image: "downtrend-structure",
        options: [
          "No errors — momentum is real",
          "6 trades is statistical noise (sample far too small), and 10% risk makes a normal losing streak account-threatening",
          "Only the sample size is wrong",
          "Only the 10% is wrong",
        ],
        correctIndex: 1,
        explanation: "Variance masquerading as skill + ruin-level sizing: the classic overconfidence combination. Edges are proven over dozens of trades and exploited at survivable size.",
      },
      {
        prompt: "Binary event tonight (earnings) on your open long: stop $1.50 away, but similar events have gapped this stock $6+. What does risk management actually dictate?",
        image: "gap-risk",
        options: [
          "The stop handles it — hold full size",
          "Manage EXPOSURE: reduce, hedge, or flatten — through gaps the position size, not the stop, is your only real control",
          "Remove the stop to avoid a gap fill",
          "Add before the number for extra upside",
        ],
        correctIndex: 1,
        explanation: "Gap risk bypasses stops entirely (Units 1 and 4 agree). A $6 gap on full size = 4× planned risk. Deliberate exposure choices through binaries are non-optional.",
      },
      {
        prompt: "A trade sets up in dead after-hours liquidity: spread is 5× normal and your realistic stop sits inside pure noise. R:R 'looks' fine on paper. Session-aware verdict?",
        image: "liquidity-sweep",
        options: [
          "Take it — paper R:R is everything",
          "Pass or wait for liquid hours: execution costs and noise-stops turn the paper edge negative in this environment",
          "Triple size to overcome the spread",
          "Sessions don't affect edges",
        ],
        correctIndex: 1,
        explanation: "Edges are conditional on environment. The same setup in the overlap versus the dead zone is two different trades — only one of which your expectancy numbers actually describe.",
      },
      {
        prompt: "Full integration: which sequence is the correct ORDER of a professional trade decision?",
        image: "downtrend-structure",
        options: [
          "Size → entry → maybe a stop → hope",
          "Condition & session check → setup + confluence stack → invalidation level → R:R filter (≥ target) → size from fixed risk % → execute with bracket orders",
          "Entry → double up if losing → exit on feelings",
          "Indicator says go → all-in",
        ],
        correctIndex: 1,
        explanation: "Every unit in one pipeline: environment, evidence, invalidation, payoff filter, sizing, execution. If any stage fails, the pipeline outputs NO TRADE — and that output is profitable.",
      },
    ],
  },

  check_discipline: {
    title: "Unit 5 check: Discipline",
    passMark: 6,
    practice: "Now apply it: play one scenario as a full dress rehearsal — pre-session go/no-go check, written rules for the session (setups allowed, daily stop in R), journal every trade with setup/R/adherence, and stop the moment your daily limit hits. Treat it exactly like real money.",
    questions: [
      {
        prompt: "Your journal (80 trades): sweep-reclaim longs +0.5R avg (40 trades); news-spike scalps -0.6R avg (40 trades). Overall you're barely negative. The data-driven move?",
        image: "liquidity-sweep",
        options: [
          "Quit — overall negative means no hope",
          "Cut the news scalps, concentrate on sweep-reclaims: the journal just revealed a profitable trader hidden inside a losing aggregate",
          "Keep both for diversification",
          "Add a third untested setup",
        ],
        correctIndex: 1,
        explanation: "This is journaling's payoff: aggregate P&L said 'failing'; grouped data said 'stop doing the one thing that bleeds'. No new knowledge required — just subtraction.",
      },
      {
        prompt: "A trade broke your entry rules and made +2R. A rule-following trade hit its stop for -1R. Grade them as PROCESS.",
        image: "downtrend-structure",
        options: [
          "The winner was good, the loser bad",
          "The -1R was a GOOD trade (paid variance, process intact); the +2R was a BAD trade (reinforced indiscipline that compounds into disaster)",
          "Both were good — one made money, one had rules",
          "Grades don't apply to trades",
        ],
        correctIndex: 1,
        explanation: "Outcome and process are different axes. The most expensive wins of your career will be the ones that taught you rules are optional.",
      },
      {
        prompt: "Mid-session, tilted after two stops, you're SURE the R:R rule is what's holding you back and want to edit the plan right now. The discipline architecture says?",
        image: "expectancy-bars",
        options: [
          "Edit it — conviction is signal",
          "Journal the idea; evaluate at the scheduled review against data; mid-session rule edits are tilt wearing a lab coat",
          "Delete the whole plan",
          "Rules change whenever feelings peak",
        ],
        correctIndex: 1,
        explanation: "The review ritual exists because in-the-moment you is the least qualified editor. Calm-you wrote the rules for exactly this moment; let calm-you amend them too.",
      },
      {
        prompt: "TRAP: fourth strategy this quarter, ~15 trades each, all abandoned mid-losing-streak. What has this trader actually learned about any of them?",
        image: "downtrend-structure",
        options: [
          "Everything important",
          "Nothing — every sample was too small for expectancy to emerge from variance; each 'failure' was likely just a normal streak",
          "That all four strategies are bad",
          "That strategy-hopping compounds returns",
        ],
        correctIndex: 1,
        explanation: "A 45%-win system produces brutal 15-trade stretches ROUTINELY while being profitable. Sample-size discipline is what makes any judgment possible at all.",
      },
      {
        prompt: "Journal cross-reference: trades tagged 'calm' run +0.3R; tagged 'frustrated' run -0.8R. Design the rule this evidence supports.",
        image: "sr-zone",
        options: [
          "Trade angrier — intensity wins",
          "A behavioral circuit-breaker: e.g. mandatory 30-min cooldown after any stop-out, and no new entries while tagged tilted — evidence-based, not vibes-based",
          "Delete the emotion column",
          "Feelings can't affect returns",
        ],
        correctIndex: 1,
        explanation: "This is psychology made engineering: a measured personal risk factor converted into a mechanical rule. Willpower not required at the moment of weakness — the rule fires instead.",
      },
      {
        prompt: "After 9 straight winners you notice the thought: 'I've cracked it — time to loosen criteria and push size.' The trained response?",
        image: "expectancy-bars",
        options: [
          "Obey it — you HAVE cracked it",
          "Flag it as the overconfidence signature: streaks are variance, criteria and sizing hold PRECISELY because the streak will end",
          "Triple size but only once",
          "Retire immediately",
        ],
        correctIndex: 1,
        explanation: "Euphoria and despair both whisper 'the rules don't apply right now'. Recognizing the whisper as a known failure mode — in both directions — is the discipline being tested.",
      },
      {
        prompt: "Final synthesis: what IS the 'edge' this whole course has been building?",
        image: "plan-loop",
        options: [
          "A secret indicator combination",
          "A closed loop — costed execution, structural setups, fixed-risk sizing, expectancy measured from an honest journal, rules that evolve only by evidence — repeated with discipline until the math compounds",
          "Prediction of the future",
          "Trading more hours than everyone else",
        ],
        correctIndex: 1,
        explanation: "No single lesson was the edge. The SYSTEM is the edge — and the discipline to run it when bored, tilted, or euphoric is what separates knowing it from earning with it.",
      },
    ],
  },

  check_fundamentals: {
    title: "Unit 6 check: Fundamentals & leverage",
    passMark: 5,
    practice: "Now apply it: in the simulator, unlock a real market and check its scenario tags. Before trading a leveraged position, state your dollar risk FIRST (1% of the account), then size to your stop — never let the leverage decide the loss.",
    questions: [
      {
        prompt: "Two companies: A has growing revenue, positive cash flow, low debt, P/E 15. B has flat revenue, negative cash flow, high debt, P/E 60. Which business is more durable?",
        options: ["B — the higher P/E", "A — real cash, growing sales, manageable debt", "Identical", "Impossible to say"],
        correctIndex: 1,
        explanation: "Durability comes from cash generation and a sound balance sheet. B is burning cash at 60× earnings — fragile if anything slips.",
      },
      {
        prompt: "A company grows profit 20%, but the market expected 30%. Likely reaction on the day?",
        options: ["Rally — profit grew", "Sell-off — it missed expectations", "No move", "Halted"],
        correctIndex: 1,
        explanation: "Price trades the gap between result and expectation. 20% against an expected 30% is a miss.",
      },
      {
        prompt: "A stock runs 40% into earnings on hype, then reports exactly in-line. Common outcome?",
        options: ["Another big rally", "Sell-off — the news was already priced in", "Delisting", "Guaranteed +10%"],
        correctIndex: 1,
        explanation: "'Buy the rumour, sell the news' — in-line results give buyers nothing new after a hype run-up.",
      },
      {
        prompt: "You control a $10,000 position on $1,000 margin (10×). The asset moves 5% against you. Impact on margin?",
        options: ["Lose 5%", "Lose ~50% — 5% × 10×", "No impact", "Lose $5"],
        correctIndex: 1,
        explanation: "5% of $10,000 = $500 = half of your $1,000 margin. Leverage multiplies the move against your collateral.",
      },
      {
        prompt: "10× leverage, no stop, a 12% overnight gap against you. Result?",
        options: ["Small recoverable loss", "Liquidation — margin wiped", "Broker covers it", "Trade pauses"],
        correctIndex: 1,
        explanation: "12% at 10× is a 120% hit to margin — past the maintenance floor. Force-closed at market, margin gone.",
      },
      {
        prompt: "The safer way to use leverage is to…",
        options: [
          "Max it out to grow faster",
          "Fix risk-per-trade (e.g. 1%) and let leverage only free up cash, never enlarge the loss at your stop",
          "Drop stops so you're never shaken out",
          "Only use it on sure things",
        ],
        correctIndex: 1,
        explanation: "Size from your stop and a fixed dollar risk. Then leverage reduces cash tied up without increasing what you lose when wrong.",
      },
    ],
  },
};
