// Each lesson is a short sequence of teach -> question steps.
// step.type: "teach" (just an explanation, tap to continue) or "question" (multiple choice)

export const LESSONS = {
  how_markets_work: {
    title: "How markets work",
    steps: [
      {
        type: "teach",
        text: "A market is buyers and sellers agreeing on price. Every trade needs a counterparty: when you buy, someone sells to you. Price moves because of imbalance — more aggressive buying pushes price up, more aggressive selling pushes it down.",
      },
      {
        type: "question",
        prompt: "Price is rising rapidly. What's actually happening?",
        image: "downtrend-structure",
        options: [
          "The exchange is raising the price",
          "Buyers are willing to pay progressively higher prices to get filled",
          "Sellers have left the market entirely",
          "The chart is drawing itself",
        ],
        correctIndex: 1,
        explanation: "Rising price means aggressive buyers are lifting whatever sellers offer, and must bid higher to keep getting filled. Price is the record of that auction.",
      },
      {
        type: "teach",
        text: "Every quote has two prices. The BID is the highest price buyers currently offer. The ASK is the lowest price sellers currently accept. The gap between them is the SPREAD.",
        image: "bid-ask",
      },
      {
        type: "question",
        prompt: "A stock shows bid $99.95 / ask $100.05. You buy at market. What do you pay?",
        image: "bid-ask",
        options: ["$99.95", "$100.00", "$100.05", "Whatever you want"],
        correctIndex: 2,
        explanation: "Buying at market means accepting the best available seller price — the ask, $100.05.",
      },
      {
        type: "question",
        prompt: "Same stock: bid $99.95 / ask $100.05. Immediately after buying at $100.05, you sell at market. What do you receive?",
        image: "downtrend-structure",
        options: ["$100.05 — what you paid", "$99.95 — the bid", "$100.00 — the midpoint", "$100.15"],
        correctIndex: 1,
        explanation: "Selling at market means accepting the best available buyer price — the bid. You just lost $0.10 per share without price moving at all. That's the spread cost.",
      },
      {
        type: "question",
        prompt: "You bought 500 shares crossing that $0.10 spread. What did the round trip cost you before the market even moved?",
        image: "bid-ask",
        options: ["$5", "$50", "$500", "Nothing"],
        correctIndex: 1,
        explanation: "500 shares × $0.10 spread = $50. This is why spread matters more the bigger and more frequent your trades.",
      },
      {
        type: "teach",
        text: "Liquidity is how much volume sits ready to trade near the current price. High liquidity (major stocks, major forex pairs at peak hours) = tight spreads and easy fills. Low liquidity (small caps, off-hours) = wide spreads and slippage.",
      },
      {
        type: "question",
        prompt: "Which situation likely has the WIDEST spread?",
        image: "bid-ask",
        options: [
          "A major index ETF at midday",
          "A large-cap tech stock at the open",
          "A small-cap stock in after-hours trading",
          "A major forex pair during London session",
        ],
        correctIndex: 2,
        explanation: "Thin instruments at thin times of day have the fewest participants, so the gap between what buyers offer and sellers accept is widest.",
      },
      {
        type: "teach",
        text: "Slippage is the difference between the price you expected and the price you actually got. It happens when price moves between your decision and your fill, or when your order is too big for the liquidity available at the best price.",
      },
      {
        type: "question",
        prompt: "You place a market buy when the ask shows $50.00, but fill at $50.08. What happened?",
        image: "downtrend-structure",
        options: [
          "The broker stole $0.08",
          "Slippage — available liquidity at $50.00 was taken before your full order filled",
          "A pricing error that will be refunded",
          "Nothing unusual can cause this",
        ],
        correctIndex: 1,
        explanation: "In fast or thin markets, the displayed price can be gone by the time your order arrives — your order 'walks up' to the next available sellers. This is normal slippage, and it's simulated in this game's fills too.",
      },
      {
        type: "question",
        prompt: "TRAP: A friend says day-trading a stock with a huge 5% spread is fine 'because it moves a lot'. What's the flaw?",
        image: "bid-ask",
        options: [
          "No flaw — volatility beats everything",
          "You start every trade 5% underwater; the move must beat the spread AND your risk just to break even",
          "Wide spreads mean the stock is safer",
          "Spreads don't apply to day trades",
        ],
        correctIndex: 1,
        explanation: "You buy at ask, sell at bid. A 5% spread means you need a 5% move in your favor just to get back to flat — before commissions. High volatility doesn't remove that toll, it just hides it.",
      },
      {
        type: "question",
        prompt: "Scenario: you trade a $10,000 account, 20 round trips per week, average spread+slippage cost of $8 per round trip. What's the yearly cost of execution alone (50 weeks)?",
        image: "bid-ask",
        options: ["$400", "$800", "$8,000", "$80"],
        correctIndex: 2,
        explanation: "20 × $8 × 50 = $8,000 — 80% of the account, just in execution costs. This is why frequency and cost-awareness decide survival long before strategy does.",
      },
      {
        type: "teach",
        text: "Takeaway: price is an auction, the spread is a toll, and liquidity decides the toll's size. Profitable trading starts with keeping the toll small relative to what you expect to make per trade.",
      },
    ],
  },

  order_types: {
    title: "Order types & execution",
    steps: [
      {
        type: "teach",
        text: "An order is your instruction to the market: what to trade, how much, and how to execute. The three core types — market, limit, and stop — differ in one fundamental trade-off: certainty of FILL versus certainty of PRICE.",
      },
      {
        type: "question",
        prompt: "Which is the fundamental trade-off between order types?",
        image: "order-map",
        options: [
          "Speed versus commission cost",
          "Certainty of getting filled versus certainty of the price you get",
          "Long versus short",
          "Stocks versus forex",
        ],
        correctIndex: 1,
        explanation: "Market orders guarantee (near enough) a fill but not a price. Limit orders guarantee your price but not a fill. Every order choice is a position on this trade-off.",
      },
      {
        type: "teach",
        text: "MARKET ORDER: fills immediately at best available price. Use when getting in or out NOW matters more than the exact price. Risk: slippage, especially in fast or thin markets.",
      },
      {
        type: "question",
        prompt: "News breaks and your stock gaps down fast. You decide the trade thesis is dead. Best tool?",
        image: "gap-risk",
        options: [
          "A limit order well above the market 'to get a good exit'",
          "A market order — certainty of exit matters more than exact price now",
          "No order — hope it recovers",
          "Double your position to average down",
        ],
        correctIndex: 1,
        explanation: "When the thesis is invalidated and price is moving against you fast, fill certainty wins. A limit above market may never fill while losses grow.",
      },
      {
        type: "teach",
        text: "LIMIT ORDER: fills only at your price or better. A buy limit goes BELOW current price, a sell limit ABOVE. Use for planned entries at levels and for taking profit. Risk: price never reaches you and the trade happens without you.",
        image: "order-map",
      },
      {
        type: "question",
        prompt: "Price is $100. You want to buy a pullback into support at $97. Which order?",
        image: "downtrend-structure",
        options: [
          "Buy limit at $97",
          "Buy stop at $97",
          "Market order now at $100",
          "Sell limit at $97",
        ],
        correctIndex: 0,
        explanation: "A buy limit at $97 rests below the market and fills only if price comes down to you — the standard tool for planned pullback entries.",
      },
      {
        type: "question",
        prompt: "TRAP: price is $100 and you place a buy LIMIT at $103 'to make sure it fills'. What actually happens?",
        image: "downtrend-structure",
        options: [
          "It waits for $103",
          "It fills immediately at the best available price (like a market order), since the market is already better than your limit",
          "It's rejected",
          "It becomes a stop order",
        ],
        correctIndex: 1,
        explanation: "A buy limit above the current ask is instantly marketable — you've built a market order with extra steps. Buy limits belong at or below market; sell limits at or above.",
      },
      {
        type: "teach",
        text: "STOP ORDER: dormant until price touches your trigger, then becomes a market order. Two jobs: (1) the stop-loss — exiting when price proves you wrong; (2) stop entries — entering on strength/weakness confirmation, e.g. a buy stop above a breakout level.",
      },
      {
        type: "question",
        prompt: "You're long from $50 and decide your idea is wrong if price trades at $48. What do you place?",
        image: "order-map",
        options: [
          "Sell limit at $48",
          "Sell stop at $48",
          "Buy stop at $48",
          "Nothing — watch it manually",
        ],
        correctIndex: 1,
        explanation: "A sell stop at $48 sits below market and triggers if price falls there, exiting you automatically. A sell LIMIT at $48 would fill immediately since the market is above it.",
      },
      {
        type: "question",
        prompt: "Your sell stop is at $48. Overnight, bad news gaps the stock open at $45. Where do you get filled?",
        image: "gap-risk",
        options: [
          "Exactly $48 — that's guaranteed",
          "Around $45 — the stop triggered on the gap and filled at the next available price",
          "The order is cancelled",
          "$50, your entry",
        ],
        correctIndex: 1,
        explanation: "A stop guarantees the ATTEMPT to exit, not the price. Through a gap, it fills at the next traded price. This gap risk is why position sizing (next unit) can't rely on the stop distance alone.",
      },
      {
        type: "question",
        prompt: "You want to buy ONLY IF price breaks above $105 resistance, confirming strength. Which order?",
        image: "sr-zone",
        options: [
          "Buy limit at $105",
          "Buy stop at $105 (or just above)",
          "Sell stop at $105",
          "Market order now",
        ],
        correctIndex: 1,
        explanation: "A buy stop above resistance triggers only when price proves strength by trading there. A buy limit at $105 would fill on any touch from below — including a rejection.",
      },
      {
        type: "question",
        prompt: "Scenario: you plan a long at $60 support, invalidation at $58, profit target $66. Which order set matches the plan?",
        image: "sr-zone",
        options: [
          "Buy limit $60, sell stop $58, sell limit $66",
          "Buy stop $60, sell limit $58, sell stop $66",
          "Three market orders",
          "Buy limit $66, sell stop $60, sell limit $58",
        ],
        correctIndex: 0,
        explanation: "Entry resting at the level (buy limit $60), stop-loss below invalidation (sell stop $58), target above (sell limit $66). This bracket is the plan expressed in orders.",
      },
      {
        type: "question",
        prompt: "TRAP: to 'avoid getting stopped out', a trader removes their stop-loss on a losing trade. What's the real effect?",
        image: "stop-bracket",
        options: [
          "The loss can no longer grow",
          "They've converted a defined, planned loss into an undefined one — the single fastest route to blowing up",
          "The trade becomes an investment, which is safer",
          "Nothing changes",
        ],
        correctIndex: 1,
        explanation: "The stop was where the idea was wrong. Removing it doesn't make the idea right — it just removes the cap on how much being wrong can cost.",
      },
      {
        type: "teach",
        text: "Takeaway: market = fill certainty, limit = price certainty, stop = conditional trigger. In this game your entries fill like market orders with slippage and commission — exactly the costs these lessons describe. Watch them eat into each trade.",
      },
    ],
  },

  risk_basics: {
    title: "Risk basics: position sizing",
    steps: [
      {
        type: "teach",
        text: "The order of operations that keeps traders alive: (1) decide the % of account you'll risk on this trade, (2) find where the idea is invalidated (stop), (3) THEN compute position size from those two. Size is an output, never an input.",
      },
      {
        type: "question",
        prompt: "Account $10,000, risking 1% per trade. What's the maximum this trade may lose?",
        image: "stop-bracket",
        options: ["$1,000", "$100", "$10", "1% of the position"],
        correctIndex: 1,
        explanation: "1% of $10,000 = $100. That's the loss if the stop is hit — the number everything else is built around.",
      },
      {
        type: "teach",
        text: "THE FORMULA: Position size = Risk amount ÷ Stop distance. Entry $50, stop $48 → stop distance $2. Risking $100 → $100 ÷ $2 = 50 shares. If the stop hits: 50 × $2 = exactly $100 lost. The math is the whole lesson.",
        image: "stop-bracket",
      },
      {
        type: "question",
        prompt: "Account $10,000, risk 1% ($100). Entry $25, stop $24. How many shares?",
        image: "stop-bracket",
        options: ["25 shares", "100 shares", "400 shares", "1,000 shares"],
        correctIndex: 1,
        explanation: "Stop distance $1. $100 ÷ $1 = 100 shares. Check: 100 shares × $1 = $100 = 1% ✓",
      },
      {
        type: "question",
        prompt: "Same account, same 1% risk. Entry $25, but this setup's stop belongs at $23 (distance $2). Shares now?",
        image: "stop-bracket",
        options: ["100 — same as before", "50 shares", "200 shares", "It's untradeable"],
        correctIndex: 1,
        explanation: "$100 ÷ $2 = 50 shares. Wider stop → smaller size, SAME dollar risk. This is the mechanism that makes stop width a sizing input rather than a danger.",
      },
      {
        type: "question",
        prompt: "TRAP: a trader always buys 500 shares 'because that's my size', wherever the stop lands. What's actually varying wildly trade to trade?",
        image: "downtrend-structure",
        options: [
          "Nothing — consistency achieved",
          "Their real dollar risk: 500 shares × a $0.50 stop risks $250; × a $3 stop risks $1,500",
          "Only the commissions",
          "The ticker symbol",
        ],
        correctIndex: 1,
        explanation: "Fixed shares + variable stops = random risk. One 'normal-feeling' trade can quietly carry 6× the risk of another. Fix the risk %, let the share count float.",
      },
      {
        type: "question",
        prompt: "Why do professionals talk in 1–2% risk per trade rather than 10%?",
        image: "stop-bracket",
        options: [
          "Regulation forces it",
          "Survivability: at 1% risk, a 10-loss streak costs ~10% of the account; at 10% risk, the same streak destroys ~65% — and streaks WILL happen",
          "They dislike money",
          "Small risk guarantees profit",
        ],
        correctIndex: 1,
        explanation: "Every strategy has losing streaks. Small per-trade risk means streaks are survivable bruises; large risk turns ordinary variance into ruin. You must survive to let any edge play out.",
      },
      {
        type: "question",
        prompt: "Drawdown math: you lose 50% of your account. What gain do you now need just to get back to even?",
        image: "stop-bracket",
        options: ["50%", "75%", "100%", "25%"],
        correctIndex: 2,
        explanation: "From $10,000 to $5,000 is -50%; getting from $5,000 back to $10,000 requires +100%. Losses hurt more than the same-sized gains help — the asymmetry behind all risk discipline.",
      },
      {
        type: "question",
        prompt: "Gap reality check (from Unit 1): your stop is $2 away, sized for $100 risk — but overnight news gaps price $5 past your stop. Actual loss?",
        image: "gap-risk",
        options: [
          "$100 — stops are guarantees",
          "About $250 — fills happen at the gap price, not the stop price",
          "$0",
          "The broker covers it",
        ],
        correctIndex: 1,
        explanation: "50 shares × $5 = $250. Stops cap NORMAL losses, not gap losses — which is one more reason per-trade risk stays small and overnight exposure gets extra thought.",
      },
      {
        type: "teach",
        text: "Takeaway: risk % first, invalidation second, size computed last. Same dollars risked on every trade regardless of stop width. Small enough to survive the streaks that are coming either way.",
      },
    ],
  },

  core_indicators: {
    title: "Core indicators",
    steps: [
      {
        type: "teach",
        text: "Indicators are math applied to past price. They summarize; they don't foresee. Used well, they add context and objectivity. Used badly, they become a slot machine of 'signals'. Rule one: price and structure lead, indicators support.",
      },
      {
        type: "question",
        prompt: "A 20-period moving average is simply…",
        image: "ma-pullback",
        options: [
          "The price 20 days in the future",
          "The average of the last 20 closes, redrawn each new bar",
          "A broker's price guarantee",
          "The maximum price of the year",
        ],
        correctIndex: 1,
        explanation: "That's all it is: a rolling average. Its value is smoothing noise so trend direction and 'normal' pullback depth become easier to see.",
      },
      {
        type: "question",
        prompt: "Price is above a rising 50-period MA, and pullbacks keep finding buyers near it. How are trend traders using that MA?",
        image: "downtrend-structure",
        options: [
          "As a magic line that cannot break",
          "As a dynamic reference for trend health and a pullback zone to look for entries",
          "As a reason to short",
          "They aren't — MAs are useless",
        ],
        correctIndex: 1,
        explanation: "In steady trends, MAs often track the pullback depth that keeps attracting buyers. That makes them a useful map reference — combined with structure, never alone.",
      },
      {
        type: "teach",
        text: "MOVING AVERAGE LAG: because MAs average the past, they turn AFTER price does. The longer the period, the smoother but later the signal. Every MA signal is late by design — the price you pay for smoothness.",
        image: "ma-pullback",
      },
      {
        type: "question",
        prompt: "TRAP: a trader waits for a 200-period MA to turn downward before considering any trend change. What's the cost of this filter?",
        image: "ma-pullback",
        options: [
          "None — later is always better",
          "Massive lag: by the time a 200 MA turns, a large part of the reversal has already happened",
          "The MA will turn before price does",
          "200 MAs update only annually",
        ],
        correctIndex: 1,
        explanation: "Long MAs confirm regimes, not turns. Structure (CHoCH, LH/LL) shifts far earlier. Choose tools knowing what they're late to.",
      },
      {
        type: "teach",
        text: "RSI measures the speed of recent gains vs losses on a 0–100 scale. Above 70 = 'overbought', below 30 = 'oversold'. The quotes matter: in strong trends, RSI can pin above 70 or below 30 for a long time while price keeps going.",
        image: "rsi-divergence",
      },
      {
        type: "question",
        prompt: "RSI has read 75–85 for three weeks during a powerful uptrend. The 'signal' many beginners take — and its usual result?",
        image: "rsi-divergence",
        options: [
          "Buy more — high RSI means strength forever",
          "Short the 'overbought' reading — and get run over as the trend continues",
          "Close the platform",
          "RSI cannot stay above 70",
        ],
        correctIndex: 1,
        explanation: "'Overbought' describes speed, not a ceiling. Fading strong trends on RSI alone is one of the most reliable ways to lose money. RSI extremes matter most in RANGES, at the edges.",
      },
      {
        type: "question",
        prompt: "Where does an RSI extreme carry the most useful information?",
        image: "rsi-divergence",
        options: [
          "Mid-trend, against the trend",
          "At the edge of an established range, agreeing with a structural level",
          "On its own, ignoring price entirely",
          "Never — delete the indicator",
        ],
        correctIndex: 1,
        explanation: "Range edge + structural level + momentum extreme = pieces agreeing. An indicator confirming a level you already had reasons to watch is context; an indicator alone is a coin flip.",
      },
      {
        type: "question",
        prompt: "DIVERGENCE: price makes a higher high, RSI makes a lower high. What is this suggesting?",
        image: "downtrend-structure",
        options: [
          "Nothing, ever",
          "The new high came with less momentum — the trend may be tiring (a clue, not a trigger)",
          "Guaranteed crash within one bar",
          "The RSI is broken",
        ],
        correctIndex: 1,
        explanation: "Divergence flags weakening thrust behind new extremes. Like a CHoCH warning, it earns attention and tighter risk — it is not, by itself, an entry.",
      },
      {
        type: "question",
        prompt: "TRAP: a trader stacks 6 indicators; all derive from the same closing prices, and all say 'buy'. How much independent confirmation is that?",
        image: "downtrend-structure",
        options: [
          "Six independent confirmations",
          "Roughly one — they're re-processing the same input, so they mostly agree by construction",
          "Zero information of any kind",
          "It depends on the color scheme",
        ],
        correctIndex: 1,
        explanation: "Indicators derived from the same price series are correlated with each other. Real confluence combines DIFFERENT kinds of evidence: structure, level, volume, momentum — not six flavors of the same math.",
      },
      {
        type: "teach",
        text: "Takeaway: know what each tool measures and what it's late to. MAs for regime and pullback maps; RSI for momentum extremes at meaningful locations; divergence as a caution flag. Indicators confirm ideas — they don't generate them.",
      },
    ],
  },

  risk_management: {
    title: "R-multiples & expectancy",
    steps: [
      {
        type: "teach",
        text: "R = the amount you risked. Every outcome can be expressed in R: risk $100, make $250 → +2.5R; lose the full stop → -1R. Thinking in R normalizes every trade so wins/losses become comparable and your system becomes measurable.",
        image: "stop-bracket",
      },
      {
        type: "question",
        prompt: "You risked $80; the trade made $200. In R?",
        image: "expectancy-bars",
        options: ["+1.2R", "+2.5R", "+4R", "-2.5R"],
        correctIndex: 1,
        explanation: "$200 ÷ $80 = 2.5R. Whether the account is $1k or $1M, +2.5R means the same thing about the QUALITY of the trade.",
      },
      {
        type: "question",
        prompt: "Planned reward:risk — entry $40, stop $38, target $46. What's the R:R of the plan?",
        image: "expectancy-bars",
        options: ["1:1", "2:1", "3:1", "6:1"],
        correctIndex: 2,
        explanation: "Risk $2, reward $6 → 3:1 (a +3R win if it hits). This number exists BEFORE entry — good trades are selected partly on it.",
      },
      {
        type: "teach",
        text: "EXPECTANCY = (win% × avg win in R) − (loss% × avg loss in R). It's the average R you make per trade over many trades. Positive expectancy after costs = a real edge. Everything else is noise.",
      },
      {
        type: "question",
        prompt: "System: 40% win rate, winners +2.5R, losers -1R. Expectancy per trade?",
        image: "expectancy-bars",
        options: [
          "-0.1R — losing system",
          "+0.4R — profitable",
          "+1.0R",
          "0R exactly",
        ],
        correctIndex: 1,
        explanation: "(0.4 × 2.5) − (0.6 × 1) = 1.0 − 0.6 = +0.4R per trade. Losing 60% of the time and being solidly profitable — this is the math most beginners never internalize.",
      },
      {
        type: "question",
        prompt: "System B: 70% win rate, winners +0.5R, losers -1R. Expectancy?",
        image: "expectancy-bars",
        options: [
          "+0.05R — barely positive, likely negative after costs",
          "+0.7R — excellent",
          "-0.5R",
          "Win rate that high can't lose",
        ],
        correctIndex: 0,
        explanation: "(0.7 × 0.5) − (0.3 × 1) = 0.35 − 0.30 = +0.05R. A 70% winner that barely survives before spread and commissions. High win rate ≠ profitable — the R sizes decide.",
      },
      {
        type: "question",
        prompt: "TRAP: to 'improve the R:R', a trader picks a target 10R away on a setup that realistically never runs that far, and a stop so tight it's inside the noise. What's wrong?",
        image: "downtrend-structure",
        options: [
          "Nothing — bigger planned R:R is always better",
          "Planned R:R only matters if the target is REACHABLE and the stop survivable; fantasy targets + noise-stops produce a great-looking plan that loses constantly",
          "Stops shouldn't exist",
          "10R targets are illegal",
        ],
        correctIndex: 1,
        explanation: "Expectancy uses ACHIEVED R, not imagined R. A tight stop inside normal fluctuation just converts good ideas into -1R outcomes. Structure decides stops and targets; the ratio is then computed, not decorated.",
      },
      {
        type: "question",
        prompt: "Your journal after 50 trades: 45% wins, avg win +1.8R, avg loss -1.05R (slippage makes losses slightly worse than -1R). Expectancy?",
        image: "expectancy-bars",
        options: [
          "+0.23R per trade — a real, measurable edge",
          "-0.23R",
          "+1.8R",
          "Can't be computed",
        ],
        correctIndex: 0,
        explanation: "(0.45 × 1.8) − (0.55 × 1.05) = 0.81 − 0.578 ≈ +0.23R. THIS is what 'having an edge' literally means — a number from your own records, not a feeling.",
      },
      {
        type: "question",
        prompt: "With +0.23R expectancy and 1% risk per trade, roughly what does 100 trades produce (ignoring compounding)?",
        image: "trend-structure",
        options: [
          "About +23% on the account",
          "About +2.3%",
          "Exactly 0%",
          "About +230%",
        ],
        correctIndex: 0,
        explanation: "100 trades × 0.23R × 1% ≈ +23%. Small positive expectancy, repeated with discipline and survivable risk, is the entire business model of trading.",
      },
      {
        type: "teach",
        text: "Takeaway: denominate everything in R. Judge systems by expectancy after costs, not by win rate. Set stops and targets from structure, then let the R:R filter which setups deserve your risk.",
      },
    ],
  },

  session_concepts: {
    title: "Trading sessions",
    steps: [
      {
        type: "teach",
        text: "Markets have a daily rhythm driven by which financial centers are awake: Asia (quieter, range-building), London (first major volume, often breaks or sweeps Asia's range), New York (biggest moves, overlaps London for a few hours, hosts most economic releases).",
      },
      {
        type: "question",
        prompt: "Which session most often builds the day's initial range that later sessions react to?",
        image: "range-vs-trend",
        options: ["New York", "London", "Asia", "None — it's uniform"],
        correctIndex: 2,
        explanation: "Lower participation during Asian hours (for Western instruments and FX majors) typically produces tighter, rangier trade — a reference box for what follows.",
      },
      {
        type: "question",
        prompt: "London opens and immediately spikes below the Asian session low — triggering stops — then reverses and rallies for hours. Which two concepts from earlier units just combined?",
        image: "downtrend-structure",
        options: [
          "Divergence and dividends",
          "A liquidity sweep of the Asian low + session-open volatility injection",
          "Support becoming a moving average",
          "Nothing recognizable",
        ],
        correctIndex: 1,
        explanation: "The Asian range's edges are marked liquidity pools. London's volume arrival is exactly when someone can afford to harvest them. Session logic tells you WHEN sweeps are most likely.",
      },
      {
        type: "teach",
        text: "The LONDON–NEW YORK OVERLAP (a few hours around the NY morning) is typically the day's deepest liquidity and largest moves. Quietest trap: the dead zone after London closes and before Asia — thin, choppy, spread-widening hours.",
      },
      {
        type: "question",
        prompt: "A day trader keeps losing money trading the hours AFTER New York's morning momentum dies down, in thin afternoon chop. The session-aware fix?",
        image: "session-clock",
        options: [
          "Trade those hours twice as hard",
          "Concentrate trading where their strategy's conditions actually occur (e.g. the overlap) and stand down in the chop",
          "Switch to a bigger size in the chop",
          "Sessions are superstition",
        ],
        correctIndex: 1,
        explanation: "The same strategy can be profitable in one session window and a bleed in another. WHEN you trade is a filter as real as any setup criterion.",
      },
      {
        type: "question",
        prompt: "How does the session lens change how you read this game's daily-bar scenarios?",
        image: "session-clock",
        options: [
          "It doesn't apply to any timeframe",
          "Daily bars each CONTAIN a full session cycle — long wicks often mark intraday session sweeps; the lesson's logic scales into how bars form",
          "Daily bars are drawn randomly",
          "Sessions delete daily charts",
        ],
        correctIndex: 1,
        explanation: "Every daily candle is a compressed session story: its wicks and body reflect which sessions pushed and which rejected. Understanding the rhythm inside the bar sharpens how you read the bar itself.",
      },
      {
        type: "question",
        prompt: "TRAP: a strategy backtested only on London-session data gets deployed 24 hours a day. Likely outcome?",
        image: "session-clock",
        options: [
          "Identical performance around the clock",
          "Degraded results — the edge was partly session-specific (volatility, spreads, participation all differ off-session)",
          "Tripled profits automatically",
          "Backtests transfer perfectly always",
        ],
        correctIndex: 1,
        explanation: "Edges are conditional on the environment that produced them. Session is one of the strongest environmental variables — test and trade in matching conditions.",
      },
      {
        type: "question",
        prompt: "A simple session framework in three steps — pick the right order:",
        image: "session-clock",
        options: [
          "Trade Asia blind → ignore London → sleep through NY",
          "Mark the Asian range → watch how London treats its edges (break & hold vs sweep & reverse) → use that read as bias into New York",
          "Mark NY's close → trade it during Asia → repeat",
          "There is no usable framework",
        ],
        correctIndex: 1,
        explanation: "Range as reference, London's behavior as the tell, NY as the payoff window. Not a guarantee — a structured way to form (and invalidate) a daily bias.",
      },
      {
        type: "teach",
        text: "Takeaway: volume and volatility follow the session clock. Know when your strategy's conditions exist, expect sweeps at session-transition liquidity points, and treat time-of-day as a first-class filter.",
      },
    ],
  },

  chart_reading_basics: {
    title: "Reading a candlestick chart",
    steps: [
      {
        type: "teach",
        text: "Each candle compresses one time period into four prices: Open, High, Low, Close (OHLC). The body spans open-to-close. The wicks mark the extremes. One candle = one complete auction story.",
        image: "candle-anatomy",
      },
      {
        type: "build_candle",
        prompt: "Build it yourself. Drag the sliders to make a bullish candle: open 50, high 55, low 49, close 54.",
        target: { open: 50, high: 55, low: 49, close: 54 },
      },
      {
        type: "question",
        prompt: "A daily candle: open $50, high $55, low $49, close $54. Describe the body.",
        image: "candle-anatomy",
        options: [
          "From $49 to $55",
          "From $50 to $54 — bullish",
          "From $50 to $54 — bearish",
          "From $54 to $55",
        ],
        correctIndex: 1,
        explanation: "Body = open to close, $50→$54. Close above open = bullish candle. The wicks ($49 low, $55 high) sit outside the body.",
      },
      {
        type: "question",
        prompt: "Same candle: open $50, high $55, low $49, close $54. What does the upper wick tell you?",
        image: "wick-rejection",
        options: [
          "Nothing",
          "Price reached $55 but sellers pushed it back to $54 by the close",
          "Buyers were absent all day",
          "The stock was halted",
        ],
        correctIndex: 1,
        explanation: "The wick from $54 to $55 shows territory price visited but couldn't hold — a modest rejection of the highs, though the candle is still firmly bullish.",
      },
      {
        type: "teach",
        text: "Candle SIZE = conviction. A large body means one side dominated the whole period. A tiny body with long wicks (a 'doji') means indecision — both sides fought to a draw.",
      },
      {
        type: "question",
        prompt: "After a strong multi-day rally, a doji forms (tiny body, long wicks both sides). Best read?",
        image: "doji",
        options: [
          "Guaranteed reversal — short immediately",
          "The one-way buying pressure has paused; watch the next candle for who wins",
          "Nothing changed — the rally must continue",
          "The market is broken",
        ],
        correctIndex: 1,
        explanation: "A doji after a trend signals the dominant side lost control — but it's a pause signal, not a trade by itself. Context and confirmation decide what happens next.",
      },
      {
        type: "question",
        prompt: "A candle has a long LOWER wick and closes near its high after dipping into a support area. What likely happened during the period?",
        image: "wick-rejection",
        options: [
          "Sellers held control throughout",
          "Price sold off, buyers stepped in at support, and drove price back up strongly",
          "No trading happened",
          "Buyers gave up at the lows",
        ],
        correctIndex: 1,
        explanation: "The path was: down, rejected, recovered. Long lower wicks at support are one of the clearest visual footprints of buyers defending a level (often called a hammer or pin bar).",
      },
      {
        type: "teach",
        text: "TIMEFRAMES: the same market draws different candles per timeframe. A 1D candle contains ~7 hourly candles. Higher timeframes filter noise and show the bigger auction; lower timeframes show the detail inside it.",
      },
      {
        type: "question",
        prompt: "A daily candle closed strongly bullish. On the hourly chart, the same day most likely shows…",
        image: "downtrend-structure",
        options: [
          "One giant candle",
          "A sequence of smaller candles that net out to that daily gain — possibly with dips along the way",
          "Nothing — hourly charts don't exist for that day",
          "All red candles",
        ],
        correctIndex: 1,
        explanation: "Lower timeframes are the anatomy of higher ones. A bullish daily can contain hours of selling — which is why traders check higher timeframes for context before trusting lower-timeframe signals.",
      },
      {
        type: "question",
        prompt: "TRAP: you spot a 'perfect' bullish hammer on the 5-minute chart, but the daily chart is in a strong downtrend below all resistance. What's the honest read?",
        image: "downtrend-structure",
        options: [
          "The 5-minute signal overrides everything — go long big",
          "A minor counter-trend blip inside a dominant downtrend — low-quality long at best",
          "The daily chart doesn't matter",
          "Hammers never fail",
        ],
        correctIndex: 1,
        explanation: "Signals carry the weight of their timeframe. A 5-minute hammer against a daily downtrend is a rowing boat against the tide. Trade signals WITH higher-timeframe context, not against it.",
      },
      {
        type: "question",
        prompt: "Volume shows 3× average on a big bullish breakout candle. Why does that matter?",
        image: "volume-conviction",
        options: [
          "It doesn't — volume is decoration",
          "High volume means broad participation, making the move more likely to be genuine rather than a thin-market blip",
          "High volume guarantees the price will fall",
          "Volume only matters on Fridays",
        ],
        correctIndex: 1,
        explanation: "Volume is the conviction meter behind the candle. Breakouts on heavy volume have real participation; breakouts on thin volume are easier to reverse.",
      },
      {
        type: "teach",
        text: "Takeaway: read candles as auction stories — who pushed, who rejected, who won — sized by volume, and always weighted by timeframe. Single candles suggest; context confirms.",
      },
    ],
  },

  support_resistance: {
    title: "Support and resistance",
    steps: [
      {
        type: "teach",
        text: "Support: a price area where declines have repeatedly stopped — buyers defend it. Resistance: where rallies repeatedly stall — sellers defend it. They're zones, not exact lines: think a price band a few ticks wide.",
        image: "sr-zone",
      },
      {
        type: "question",
        prompt: "Price bounced at $98.80, $99.10, and $99.05 across three separate declines. Where's support?",
        image: "sr-zone",
        options: [
          "Exactly $98.80",
          "A zone roughly spanning $98.80–$99.10",
          "$100 — round numbers only",
          "There is no support",
        ],
        correctIndex: 1,
        explanation: "Three bounces in a tight band define a support ZONE. Treating it as one exact line leads to premature entries and stops placed inside the noise.",
      },
      {
        type: "mark_chart",
        prompt: "Your turn. Tap the chart where the price keeps finding support.",
        kind: "support",
        target_price: 99,
        tolerance: 1.2,
        bars: [
          { o: 103, h: 104, l: 102, c: 102.5 },
          { o: 102.5, h: 103, l: 100, c: 100.2 },
          { o: 100.2, h: 101, l: 99.1, c: 99.6 },
          { o: 99.6, h: 102, l: 99.3, c: 101.8 },
          { o: 101.8, h: 103.5, l: 101.5, c: 103 },
          { o: 103, h: 104, l: 102, c: 102.2 },
          { o: 102.2, h: 102.6, l: 99.2, c: 99.5 },
          { o: 99.5, h: 101.5, l: 99.0, c: 101 },
          { o: 101, h: 102, l: 100.5, c: 101.6 },
          { o: 101.6, h: 103, l: 101, c: 102.8 },
          { o: 102.8, h: 103.2, l: 101.8, c: 102 },
          { o: 102, h: 102.3, l: 99.1, c: 99.7 },
          { o: 99.7, h: 101, l: 99.2, c: 100.8 },
          { o: 100.8, h: 102.5, l: 100.5, c: 102.2 },
        ],
      },
      {
        type: "teach",
        text: "Why levels work: memory and orders. Traders who missed the last bounce leave buy orders there; trapped shorts cover there; stop clusters sit just beyond. The more visible the level, the more orders gather around it.",
      },
      {
        type: "question",
        prompt: "Which level likely carries the MOST weight?",
        image: "sr-zone",
        options: [
          "A level touched once, three years ago, on low volume",
          "A level tested multiple times recently, visible on the daily chart, near a round number",
          "A random price with no history",
          "Any diagonal line you can draw",
        ],
        correctIndex: 1,
        explanation: "Weight comes from recency, number of clean reactions, timeframe visibility, and confluence (e.g. a round number). More eyes on a level = more orders at it.",
      },
      {
        type: "teach",
        text: "ROLE REVERSAL: broken support tends to become resistance, and broken resistance becomes support. Trapped traders exiting at breakeven plus breakout traders re-entering on the retest both create orders at the old level.",
        image: "role-reversal",
      },
      {
        type: "question",
        prompt: "Price breaks decisively below $200 support, then rallies back to $200. What's the higher-probability behavior there?",
        image: "downtrend-structure",
        options: [
          "It slices straight back up through — old support always holds",
          "Sellers defend $200 (old support acting as new resistance); rejection is likely",
          "$200 is now meaningless",
          "Price teleports past it",
        ],
        correctIndex: 1,
        explanation: "The retest of broken support from below is a classic short location: bagholders sell to escape at breakeven and breakout sellers reload. Nothing is certain — but the odds favor rejection.",
      },
      {
        type: "question",
        prompt: "Scenario: you want to long a bounce at $150 support. Where does the stop-loss logically belong?",
        image: "downtrend-structure",
        options: [
          "At $150 exactly",
          "Somewhat below the zone — e.g. $148.50 — where the support idea is genuinely invalidated",
          "Above your entry at $152",
          "No stop needed at support",
        ],
        correctIndex: 1,
        explanation: "The trade thesis is 'the zone holds'. It's only proven wrong when price clearly breaks below the zone — so the stop lives below it, outside the noise, not on the line itself.",
      },
      {
        type: "question",
        prompt: "TRAP: price touches your support level for the 7th time in two weeks, each bounce weaker than the last. A friend says 'it's held 6 times, it's rock solid'. Better read?",
        image: "sr-zone",
        options: [
          "Agreed — more touches always mean stronger support",
          "Repeated rapid tests with weakening bounces suggest buyers there are being exhausted — the level may be about to fail",
          "Support can never break",
          "The 7th touch is always the strongest",
        ],
        correctIndex: 1,
        explanation: "Each test consumes the resting buy orders at the level. Frequent, weakening bounces mean demand is thinning. Strong levels are the ones that produce POWERFUL reactions, not just many touches.",
      },
      {
        type: "question",
        prompt: "You mark support at $75 on the daily chart. On the 5-minute chart, price is chopping around $75.20. What do you actually expect AT the zone?",
        image: "downtrend-structure",
        options: [
          "A perfect single-tick bounce at exactly $75.00",
          "Messy two-sided trading around the zone, possibly brief pokes below, before any clean reaction",
          "Instant reversal with no noise",
          "Support means price cannot reach $75",
        ],
        correctIndex: 1,
        explanation: "Zones are battlegrounds. Expect noise, wicks, and small violations inside them. This is why stops go beyond the zone and entries can wait for the reaction rather than the touch.",
      },
      {
        type: "teach",
        text: "Takeaway: mark zones, not lines. Weight them by reactions, recency, and visibility. Plan entries around the reaction, stops beyond the zone, and treat broken levels as candidates for role reversal.",
      },
    ],
  },

  trends_conditions: {
    title: "Trends & market conditions",
    steps: [
      {
        type: "teach",
        text: "Every market is doing one of three things: TRENDING (directional, making progress), RANGING (oscillating between boundaries), or TRANSITIONING (a trend losing steam or a range breaking). The first read on any chart is: which one is this?",
        image: "range-vs-trend",
      },
      {
        type: "question",
        prompt: "Price makes: high $110 → low $104 → high $116 → low $109 → high $122. What condition is this?",
        image: "range-vs-trend",
        options: [
          "A range",
          "An uptrend — higher highs and higher lows",
          "A downtrend",
          "Pure chaos",
        ],
        correctIndex: 1,
        explanation: "Successively higher highs (110→116→122) and higher lows (104→109) is the definition of an uptrend.",
      },
      {
        type: "compare",
        prompt: "Same market, two timeframes. The daily trends cleanly up; the 1-minute view of that same move looks choppy. What's the lesson?",
        charts: [
          {
            caption: "Daily — zoomed out",
            bars: [
              { o: 100, h: 103, l: 99, c: 102 },
              { o: 102, h: 105, l: 101, c: 104 },
              { o: 104, h: 107, l: 103, c: 106.5 },
              { o: 106.5, h: 108, l: 105, c: 105.5 },
              { o: 105.5, h: 109, l: 105, c: 108 },
              { o: 108, h: 111, l: 107, c: 110 },
              { o: 110, h: 113, l: 109, c: 112 },
              { o: 112, h: 115, l: 111, c: 114 },
            ],
          },
          {
            caption: "1-minute — zoomed in",
            bars: [
              { o: 112, h: 113, l: 111.5, c: 111.7 },
              { o: 111.7, h: 112.5, l: 111, c: 112.3 },
              { o: 112.3, h: 112.6, l: 111.2, c: 111.4 },
              { o: 111.4, h: 112.8, l: 111.3, c: 112.6 },
              { o: 112.6, h: 113, l: 112, c: 112.1 },
              { o: 112.1, h: 112.4, l: 111.4, c: 111.6 },
              { o: 111.6, h: 112.9, l: 111.5, c: 112.8 },
              { o: 112.8, h: 113.2, l: 112.2, c: 112.5 },
              { o: 112.5, h: 112.7, l: 111.6, c: 111.9 },
              { o: 111.9, h: 113.1, l: 111.7, c: 113 },
              { o: 113, h: 113.4, l: 112.3, c: 112.4 },
              { o: 112.4, h: 113, l: 112, c: 112.9 },
            ],
          },
        ],
        options: [
          "The daily chart must be wrong",
          "Higher timeframes show the trend; lower timeframes show noise that can shake you out of a good position",
          "You should only ever trade the 1-minute",
          "The two charts are unrelated markets",
        ],
        correctIndex: 1,
        explanation: "Same market, two lenses. The trend is obvious zoomed out but buried in noise zoomed in. Fighting the higher-timeframe trend on a tiny timeframe is how you get chopped up and stopped out of moves that were going your way.",
      },
      {
        type: "question",
        prompt: "Price bounces between roughly $48 and $52 nine times over a month. Which trades fit this condition?",
        image: "trend-structure",
        options: [
          "Buy every breakout above $52 aggressively",
          "Fade the edges — buy near $48, sell near $52 — until the range clearly breaks",
          "Buy the middle at $50 for maximum confusion",
          "Trend-following with wide stops",
        ],
        correctIndex: 1,
        explanation: "In an established range, edges are where the odds live: buy support, sell resistance, invalidate beyond the boundary. Breakout chasing in a range is how accounts get chopped up.",
      },
      {
        type: "teach",
        text: "TRENDS move in waves: impulse (with the trend) then pullback (against it). Pullbacks in a healthy uptrend are shallow-to-moderate and find buyers at logical places — prior structure, zones, moving averages. The lowest-risk trend entries are usually on pullbacks, not chases.",
      },
      {
        type: "question",
        prompt: "Strong uptrend. Price just spiked 8% in two days and is far above any support. Best action for a would-be buyer?",
        image: "sr-zone",
        options: [
          "Chase it now with a huge position — momentum never pauses",
          "Wait for a pullback toward structure, where risk can be defined against a real level",
          "Short it because it's 'too high'",
          "Set a buy order 20% higher",
        ],
        correctIndex: 1,
        explanation: "Chasing extended moves means entering where the next pullback starts and having no nearby invalidation. Patience for a pullback gives both a better price AND a logical stop.",
      },
      {
        type: "question",
        prompt: "TRAP: 'It's gone up so much, it MUST come down soon.' What's wrong with shorting purely on this?",
        image: "range-vs-trend",
        options: [
          "Nothing — overextension is a complete strategy",
          "Trends regularly persist far longer than feels reasonable; 'too high' is an opinion, not an invalidation level",
          "Shorting is illegal",
          "Up-moves reverse on a fixed schedule",
        ],
        correctIndex: 1,
        explanation: "'Overextended' has no defined risk point — price can keep trending while you bleed. Counter-trend trades need actual reversal evidence (structure breaking), not discomfort with the move.",
      },
      {
        type: "question",
        prompt: "You've taken 4 straight losses buying breakouts that reversed on you. Zooming out, price has been inside $95–$105 for six weeks. What was the real error?",
        image: "range-vs-trend",
        options: [
          "Bad luck, nothing more",
          "Applying a trend/breakout playbook inside a range — a condition mismatch",
          "Position size was too small",
          "The market was wrong",
        ],
        correctIndex: 1,
        explanation: "The losses weren't the strategy failing — they were the wrong strategy for the condition. Diagnosing the condition FIRST is what tells you which playbook applies.",
      },
      {
        type: "question",
        prompt: "An uptrend's pullbacks start getting deeper, rallies get shorter, and price begins closing below the levels that previously launched bounces. What's this?",
        image: "downtrend-structure",
        options: [
          "A healthier, stronger trend",
          "Early evidence of transition — the trend may be ending, tighten risk or stand aside",
          "Meaningless noise, always",
          "A guaranteed crash",
        ],
        correctIndex: 1,
        explanation: "Character change — deeper pullbacks, weaker impulses, failing support — is how transitions announce themselves. It's not a reversal signal by itself, but it's the cue to stop treating it as a clean trend.",
      },
      {
        type: "question",
        prompt: "In the simulator, bars start playing and you feel the urge to trade immediately. Per this lesson, what's the disciplined first step?",
        image: "range-vs-trend",
        options: [
          "Trade within 3 bars, always — speed wins",
          "Watch until you can name the condition (trend / range / transition), then apply the matching playbook",
          "Go long by default",
          "Max size on the first candle",
        ],
        correctIndex: 1,
        explanation: "No condition read = no playbook = gambling. The few bars of patience it takes to classify the market is the cheapest edge you'll ever get.",
      },
      {
        type: "teach",
        text: "Takeaway: classify first — trend, range, or transition. Trends: buy pullbacks to structure. Ranges: fade the edges. Transitions: reduce risk and wait for clarity. Strategy quality is condition-fit, not complexity.",
      },
    ],
  },

  market_structure: {
    title: "Market structure",
    steps: [
      {
        type: "teach",
        text: "Market structure is the skeleton of a trend: the sequence of swing highs and swing lows. Uptrend = higher highs (HH) + higher lows (HL). Downtrend = lower highs (LH) + lower lows (LL). Everything else in technical trading hangs off this skeleton.",
        image: "trend-structure",
      },
      {
        type: "question",
        prompt: "Swings: low $40 → high $48 → low $43 → high $52 → low $46. Label the structure.",
        image: "trend-structure",
        options: [
          "Downtrend: LH + LL",
          "Uptrend: HH ($48→$52) and HL ($40→$43→$46)",
          "A perfect range",
          "Unreadable",
        ],
        correctIndex: 1,
        explanation: "Highs rising (48→52), lows rising (40→43→46): textbook uptrend structure. Each HL is where buyers stepped in earlier than before.",
      },
      {
        type: "teach",
        text: "BREAK OF STRUCTURE (BOS): price breaks the most recent swing high in an uptrend (or swing low in a downtrend) — the trend confirming continuation. Each BOS says the dominant side is still in charge.",
      },
      {
        type: "question",
        prompt: "Uptrend with last swing high at $52 and last HL at $46. Price pushes to $53.50. What just happened?",
        image: "trend-structure",
        options: [
          "Change of character — the trend reversed",
          "Break of structure — uptrend continuation confirmed",
          "Nothing notable",
          "A liquidity crisis",
        ],
        correctIndex: 1,
        explanation: "Breaking the prior swing high WITH the trend is a BOS: continuation. The pullback that follows it (forming a new HL) is where trend traders look for entries.",
      },
      {
        type: "teach",
        text: "CHANGE OF CHARACTER (CHoCH): the first break AGAINST the prevailing structure — e.g. in an uptrend, price breaks below the most recent higher low. It's the earliest warning the trend may be over. Warning, not proof.",
        image: "choch",
      },
      {
        type: "question",
        prompt: "Same uptrend, HL at $46. Price now closes decisively at $44.80. What's the correct label and response?",
        image: "trend-structure",
        options: [
          "BOS — buy more aggressively",
          "CHoCH — the uptrend's structure is broken; stop treating it as a clean uptrend and reassess",
          "A guaranteed downtrend — short everything instantly",
          "Ignore it",
        ],
        correctIndex: 1,
        explanation: "Breaking the higher low is a change of character: the buy-the-dip structure failed. It doesn't guarantee reversal — but continuing to trade it as a healthy uptrend ignores the evidence.",
      },
      {
        type: "question",
        prompt: "After a CHoCH in an uptrend, what sequence would CONFIRM a new downtrend forming?",
        image: "choch",
        options: [
          "An immediate new all-time high",
          "Price setting a lower high, then breaking to a lower low",
          "Three green candles",
          "Volume dropping to zero",
        ],
        correctIndex: 1,
        explanation: "One break is a warning; a new LH followed by a LL is the downtrend actually building its own structure. Traders wanting confirmation wait for this sequence rather than shorting the first break.",
      },
      {
        type: "question",
        prompt: "TRAP: price pokes $0.10 above a swing high on one 1-minute wick, then collapses back. A trader declares 'BOS! Trend confirmed up!' What's the issue?",
        image: "wick-rejection",
        options: [
          "Nothing — any touch counts",
          "A marginal wick-through on a tiny timeframe is weak evidence — closes beyond the level and the timeframe you actually trade matter",
          "BOS requires exactly $1.00 of movement",
          "Swing highs can't be broken",
        ],
        correctIndex: 1,
        explanation: "Structure breaks are judged by conviction: clean closes beyond the level on your trading timeframe. Wick-pokes that instantly reverse are more often liquidity grabs than genuine breaks (next lessons cover why).",
      },
      {
        type: "question",
        prompt: "Practical: in an uptrend after a fresh BOS, where's the highest-quality long entry zone?",
        image: "trend-structure",
        options: [
          "Immediately at the breakout price, chasing",
          "On the pullback — as price sets a new higher low around prior structure",
          "Below the last higher low",
          "There is no such thing as entry quality",
        ],
        correctIndex: 1,
        explanation: "Post-BOS pullbacks let you buy with the trend, at structure, with the stop tucked under the forming HL — defined risk with the skeleton on your side.",
      },
      {
        type: "question",
        prompt: "Multi-step: you're long in an uptrend. Price makes a lower high at $58 (prior high $60), then breaks the $54 higher low. Structure says what about your position?",
        image: "downtrend-structure",
        options: [
          "Everything is fine — hold and hope",
          "LH + broken HL = the uptrend that justified the position is gone; the exit case is strong",
          "Add double the size",
          "Structure never applies to open positions",
        ],
        correctIndex: 1,
        explanation: "The position was a bet on the uptrend's structure. LH plus a CHoCH means that bet's premise is dead. Exiting on structural failure — not on hope — is what separates process from gambling.",
      },
      {
        type: "teach",
        text: "Takeaway: track swings, label HH/HL or LH/LL, treat BOS as continuation and CHoCH as a warning shot. Enter on pullbacks after BOS; reassess or exit when structure breaks against you.",
      },
    ],
  },

  supply_demand_zones: {
    title: "Supply and demand zones",
    steps: [
      {
        type: "teach",
        text: "A DEMAND zone is where a sharp rally launched — evidence big buying interest lived there. A SUPPLY zone is where a sharp decline launched. The sharper and further the move away, the more significant the zone: strong departures imply orders that couldn't fully fill.",
        image: "supply-demand",
      },
      {
        type: "question",
        prompt: "Price drifts sideways at $30–$31 for days, then explodes to $38 in two sessions. What did that base likely become?",
        image: "session-clock",
        options: [
          "A supply zone",
          "A demand zone at $30–$31 — where the buying that launched the rally accumulated",
          "Nothing of note",
          "A resistance line only",
        ],
        correctIndex: 1,
        explanation: "Consolidation followed by an explosive departure marks where large buying built up. Unfilled buy interest often remains, making the zone a watchpoint on any return.",
      },
      {
        type: "question",
        prompt: "Why does price often react when RETURNING to a zone it launched from?",
        image: "supply-demand",
        options: [
          "Charts have gravity",
          "Unfilled orders and traders who missed the first move are waiting there to act",
          "Exchanges force it to",
          "Pure coincidence every time",
        ],
        correctIndex: 1,
        explanation: "Institutions rarely fill size in one go; leftover orders rest at the origin. Add traders who watched the launch and want the 'second chance' — the zone becomes self-fulfilling to a degree.",
      },
      {
        type: "teach",
        text: "FRESHNESS: each retest consumes resting orders. A zone's first retest is its highest-probability reaction; by the third or fourth visit, the fuel is largely spent. Fresh zone > tested zone > exhausted zone.",
      },
      {
        type: "question",
        prompt: "Two demand zones: Zone A launched a big rally and has never been revisited. Zone B has been tapped four times with progressively weaker bounces. Which deserves more trust?",
        image: "downtrend-structure",
        options: [
          "Zone B — more touches means stronger",
          "Zone A — fresh, with its original orders likely intact",
          "Both equally",
          "Neither can ever work",
        ],
        correctIndex: 1,
        explanation: "Same logic as support exhaustion: every visit eats the resting orders. Freshness is a core quality filter for zones.",
      },
      {
        type: "question",
        prompt: "Grading zones: which departure marks the STRONGEST zone?",
        image: "supply-demand",
        options: [
          "A slow drift away over two weeks",
          "An explosive, high-volume move that left the zone in one or two candles and traveled far",
          "A move that immediately came back into the zone",
          "Departure speed is irrelevant",
        ],
        correctIndex: 1,
        explanation: "The violence of the departure is the footprint of how unbalanced the orders were. Fast, far, high-volume departures = the strongest evidence of real interest at the origin.",
      },
      {
        type: "question",
        prompt: "Scenario: price returns to a fresh daily demand zone at $84–$86 in an overall uptrend. Build the trade.",
        image: "downtrend-structure",
        options: [
          "Short at $86 with no stop",
          "Look for longs in the zone as buyers react, stop below ~$83.50 (zone invalidated), target toward prior highs",
          "Buy at $95 — far above the zone — for safety",
          "Wait for the zone to break, then buy the breakdown",
        ],
        correctIndex: 1,
        explanation: "Trend-aligned, fresh zone, defined invalidation below it, target at logical structure: that's the whole zone playbook in one trade.",
      },
      {
        type: "question",
        prompt: "TRAP: price slices straight through your demand zone and closes well below it on strong volume. What now?",
        image: "volume-conviction",
        options: [
          "Buy more — the zone owes you a bounce",
          "The zone failed; its story is over, and the failure itself is information (supply is in control there now)",
          "Move the zone lower until it 'works'",
          "Zones cannot fail",
        ],
        correctIndex: 1,
        explanation: "A conviction break through demand means the buyers you were betting on are gone or overwhelmed. Failed zones often flip roles. Redrawing zones to avoid admitting failure is curve-fitting your own hope.",
      },
      {
        type: "question",
        prompt: "How do supply/demand zones relate to the support/resistance you learned earlier?",
        image: "supply-demand",
        options: [
          "They're unrelated concepts",
          "Same underlying phenomenon — clustered orders at remembered prices — with zones emphasizing the ORIGIN of explosive moves",
          "Zones replace all other analysis",
          "S/R only works on Tuesdays",
        ],
        correctIndex: 1,
        explanation: "Both describe where orders concentrate. Horizontal S/R finds repeated reaction prices; zone analysis finds untested origins of imbalance. Strongest levels are usually both at once.",
      },
      {
        type: "teach",
        text: "Takeaway: grade zones by departure strength, freshness, and trend alignment. Trade the reaction with invalidation just beyond the zone — and when a zone fails on conviction, believe the failure.",
      },
    ],
  },

  liquidity_concepts: {
    title: "Liquidity and stop hunts",
    steps: [
      {
        type: "teach",
        text: "Liquidity = resting orders. Stops cluster in predictable places: just below swing lows and support (longs' stops), just above swing highs and resistance (shorts' stops). Those clusters are fuel — and large players need fuel to fill size.",
      },
      {
        type: "question",
        prompt: "Where is the densest pool of SELL orders (stops) most likely resting?",
        image: "downtrend-structure",
        options: [
          "Randomly scattered everywhere",
          "Just below an obvious, widely-watched swing low",
          "Exactly at the current price",
          "At round numbers above the highs",
        ],
        correctIndex: 1,
        explanation: "Every trader who bought the level puts their stop just under it — creating a dense, predictable pocket of sell orders below the low.",
      },
      {
        type: "teach",
        text: "Why sweeps happen: a fund wanting to BUY big needs sellers. Pushing price below a swing low triggers the stop cluster — a burst of forced selling — into which the fund fills its buys. Price then often reverses hard, leaving a long wick. That's a liquidity sweep / stop hunt.",
        image: "liquidity-sweep",
      },
      {
        type: "question",
        prompt: "Price dips $0.30 under a major swing low, triggers stops, then reverses violently and closes back above the level. What most likely just happened?",
        image: "trend-structure",
        options: [
          "A genuine breakdown that failed by accident",
          "A liquidity sweep — stops below the low were harvested to fill large buy orders",
          "The exchange glitched",
          "Nothing describable",
        ],
        correctIndex: 1,
        explanation: "Poke below, stop-burst, sharp reclaim = the classic sweep signature. The wick below the low is the receipt.",
      },
      {
        type: "question",
        prompt: "How does a sweep DIFFER from a real breakdown?",
        image: "liquidity-sweep",
        options: [
          "They're identical",
          "A sweep rejects and RECLAIMS the level quickly; a real breakdown holds below it and builds acceptance (closes, retests from beneath)",
          "Breakdowns only happen at noon",
          "Sweeps are always larger in size",
        ],
        correctIndex: 1,
        explanation: "The dividing line is acceptance. Reclaimed fast = sweep. Sustained trade below with the level now acting as resistance = genuine break.",
      },
      {
        type: "question",
        prompt: "Practical stop placement: given sweep behavior, where's the smarter stop for a long against a swing low at $70.00?",
        image: "liquidity-sweep",
        options: [
          "Exactly $69.99 — as tight as possible",
          "With buffer beyond the obvious pocket — e.g. $69.40 — sized so the position still respects your risk limit",
          "No stop at all",
          "Above your entry",
        ],
        correctIndex: 1,
        explanation: "Stops at the obvious spot ARE the liquidity. Buffer past the sweep pocket costs a wider stop — which you pay for with a SMALLER position, not with more account risk.",
      },
      {
        type: "question",
        prompt: "TRAP: your long gets swept out for a small loss, then price reverses and rallies exactly as you'd predicted. The correct takeaway?",
        image: "downtrend-structure",
        options: [
          "The market is rigged against you personally — quit",
          "Your stop sat inside the liquidity pocket; the read was fine, the placement wasn't. Adjust placement, keep the process",
          "Never use stops again",
          "Revenge trade at double size immediately",
        ],
        correctIndex: 1,
        explanation: "Being swept isn't persecution — it's feedback about placement. The fix is structural (buffer, sizing), never emotional (no stops, revenge).",
      },
      {
        type: "question",
        prompt: "Advanced entry: some traders WAIT for the sweep of a low before buying, rather than buying the low itself. Why?",
        image: "liquidity-sweep",
        options: [
          "It feels more dramatic",
          "Post-sweep, the stop-fuel below is spent and large buyers have shown their hand — often a cleaner low with clearer invalidation",
          "Sweeps guarantee profits",
          "Waiting is always wrong",
        ],
        correctIndex: 1,
        explanation: "Buying AFTER the flush means the forced sellers are done and the reclaim is your confirmation. Invalidation becomes crisp: back below the sweep low means the idea's wrong.",
      },
      {
        type: "question",
        prompt: "Connect the units: a 'BOS' that turns out to be a one-wick poke above a high, instantly reversing — through the liquidity lens, that was likely…",
        image: "wick-rejection",
        options: [
          "A confirmed trend continuation",
          "A sweep of buy-stops above the high, not a genuine structural break",
          "Proof structure analysis is useless",
          "A dividend event",
        ],
        correctIndex: 1,
        explanation: "This is why marginal wick-breaks make bad BOS signals: the stops above the high are exactly what got harvested. Structure + liquidity together read the chart better than either alone.",
      },
      {
        type: "teach",
        text: "Takeaway: obvious levels attract stops; stops attract sweeps. Place stops beyond the pocket (and size down accordingly), judge breaks by acceptance not by pokes, and treat swept levels as information, not injustice.",
      },
    ],
  },

  fundamentals_news: {
    title: "Fundamentals & news",
    steps: [
      {
        type: "teach",
        text: "Charts show WHAT price is doing; fundamentals and news are often WHY it moves — earnings, central-bank decisions, jobs and inflation data, geopolitical shocks. A technical trader doesn't need to predict the news; they need to know when it's scheduled and what it does to conditions.",
      },
      {
        type: "question",
        prompt: "What happens to spreads and slippage in the seconds around a major scheduled release (e.g. a rate decision)?",
        image: "bid-ask",
        options: [
          "They tighten — more efficiency",
          "Spreads blow out and slippage spikes as liquidity providers pull back from uncertainty",
          "Nothing changes",
          "Trading halts globally",
        ],
        correctIndex: 1,
        explanation: "Market makers widen or vanish into the release. Every execution cost from Unit 1 temporarily multiplies — the worst possible moment for casual market orders.",
      },
      {
        type: "question",
        prompt: "You hold a long with a stop $1 below. A binary event (earnings) hits tonight. What's the honest risk picture?",
        image: "news-spike",
        options: [
          "Max loss is $1 × shares — stops guarantee it",
          "Gap risk: price can open far beyond the stop, making the real worst case a multiple of planned risk",
          "Earnings can only push price up",
          "Stops work faster during gaps",
        ],
        correctIndex: 1,
        explanation: "Binary events gap. Unit 1's gap lesson + Unit 4's sizing lesson converge here: through events, exposure — not the stop — is your real risk control (reduce, hedge, or flatten).",
      },
      {
        type: "teach",
        text: "PRICED IN: markets move on expectations. If everyone expects a rate cut and it arrives, the reaction may be muted or even opposite ('sell the news'). The surprise — the gap between expectation and outcome — moves price, not the headline itself.",
      },
      {
        type: "question",
        prompt: "A company reports record profits, yet the stock drops 8%. Most likely explanation?",
        image: "plan-loop",
        options: [
          "Markets are simply irrational",
          "Expectations were even higher — the 'good' number was a negative SURPRISE relative to what was priced in",
          "Profits always cause drops",
          "A charting error",
        ],
        correctIndex: 1,
        explanation: "Price had already absorbed the expected good news. Reality merely matching or slightly missing lofty expectations = disappointment. Trade the surprise, not the adjective.",
      },
      {
        type: "question",
        prompt: "TRAP: 30 seconds after a data release, price whips $2 up then $3 down. A trader jumps in 'to catch the move'. What are they actually fighting?",
        image: "downtrend-structure",
        options: [
          "A calm, orderly market",
          "Algorithmic repricing at machine speed, huge spreads, and slippage — a coin flip with terrible execution",
          "Guaranteed easy money",
          "Nothing — releases are quiet",
        ],
        correctIndex: 1,
        explanation: "The first minutes of a major release are dominated by machines repricing. Many event traders wait for the dust to settle and trade the POST-news structure instead of the spike itself.",
      },
      {
        type: "question",
        prompt: "The practical weekly habit this lesson demands — even for a purely technical trader:",
        image: "news-spike",
        options: [
          "Memorize every economic statistic",
          "Check the economic calendar: know which days/hours carry high-impact events for what you trade, and plan exposure around them",
          "Watch financial TV all day",
          "Ignore all scheduled events",
        ],
        correctIndex: 1,
        explanation: "Five minutes with the calendar converts ambushes into scheduled weather. You don't need a forecast — you need to know when the storm window opens.",
      },
      {
        type: "question",
        prompt: "How do news shocks interact with the levels and zones you've mapped?",
        image: "news-spike",
        options: [
          "News deletes all technicals permanently",
          "Events often provide the ENERGY that finally breaks a level or violently sweeps one — technicals frame the map, news supplies the catalyst",
          "Levels repel all news",
          "They're unrelated realms",
        ],
        correctIndex: 1,
        explanation: "The cleanest breaks and the nastiest sweeps frequently coincide with catalysts. Map from technicals, timing-awareness from the calendar — together they explain days that neither explains alone.",
      },
      {
        type: "teach",
        text: "Takeaway: know the calendar, respect gap and spread behavior around events, size exposure through binaries deliberately, and remember it's the surprise versus expectations — not the headline — that moves price.",
      },
    ],
  },

  trade_journaling: {
    title: "Journaling your trades",
    steps: [
      {
        type: "teach",
        text: "Your journal is the dataset your edge is computed from. Without it, 'my strategy works' is a feeling; with it, expectancy (Unit 4) becomes a number. Minimum fields per trade: setup type, condition (trend/range), entry, stop, target, size, planned R:R, achieved R, rule adherence (Y/N), and one line on your state of mind.",
      },
      {
        type: "question",
        prompt: "Why record SETUP TYPE on every trade rather than just P&L?",
        image: "plan-loop",
        options: [
          "It makes the spreadsheet prettier",
          "So results can be grouped by setup — revealing which specific patterns carry your edge and which quietly bleed",
          "Regulators require it",
          "Setup type is unknowable",
        ],
        correctIndex: 1,
        explanation: "Aggregate P&L hides everything. Grouped by setup, your data might show pullback-longs at +0.5R/trade while breakout-trades run -0.3R — one insight worth more than a year of new indicators.",
      },
      {
        type: "question",
        prompt: "Your journal (60 trades): pullback entries +0.45R avg over 30 trades; range fades -0.25R avg over 30 trades. The evidence-based move?",
        image: "downtrend-structure",
        options: [
          "Change nothing — variety is strength",
          "Concentrate on pullbacks; cut or paper-trade the fades until you find why they fail",
          "Quit both and find a new strategy weekly",
          "Double size on the losing setup to win it back",
        ],
        correctIndex: 1,
        explanation: "This is journaling's whole purpose: reallocating risk from what measurably loses toward what measurably works. The journal made the decision for you.",
      },
      {
        type: "teach",
        text: "RULE ADHERENCE is its own column because outcome and process are different axes: a rule-following loss is a GOOD trade (paid variance); a rule-breaking win is a BAD trade (rewarded indiscipline — the most expensive reward you'll ever receive).",
      },
      {
        type: "question",
        prompt: "Why is a rule-breaking WIN dangerous rather than lucky?",
        image: "plan-loop",
        options: [
          "It isn't — money is money",
          "It reinforces the exact behavior that, repeated, produces the catastrophic losses your rules exist to prevent",
          "Winners can't be wrong",
          "Rules are only for losers",
        ],
        correctIndex: 1,
        explanation: "Slot machines work by intermittent reward. A win for breaking rules trains your brain to break them again — and unbounded rule-breaking eventually meets an unbounded loss.",
      },
      {
        type: "question",
        prompt: "TRAP: a trader journals only winning trades 'to stay positive'. What does their expectancy calculation now produce?",
        image: "expectancy-bars",
        options: [
          "A conservative estimate",
          "Fiction — expectancy requires ALL outcomes; censored data makes every metric meaningless",
          "The same number as full data",
          "Faster profits",
        ],
        correctIndex: 1,
        explanation: "Survivorship-biased journals are worse than none: they produce confident, wrong numbers. The painful entries are the ones carrying the most information.",
      },
      {
        type: "question",
        prompt: "The emotional-state column, reviewed monthly, shows: trades tagged 'frustrated' average -0.8R; trades tagged 'calm' average +0.3R. What did the journal just find?",
        image: "trend-structure",
        options: [
          "Astrology",
          "A measurable, personal risk factor — a rule like 'no new trades within 30 min of a stop-out' now has evidence behind it",
          "Nothing usable",
          "That feelings improve returns",
        ],
        correctIndex: 1,
        explanation: "Journals catch patterns in YOU, not just the market. Turning 'I trade badly when tilted' from a suspicion into a number is how behavioral rules earn their place.",
      },
      {
        type: "question",
        prompt: "In this simulator, what's the equivalent practice?",
        image: "plan-loop",
        options: [
          "Play fast and remember nothing",
          "After each session, note the setups taken, whether each had the full confluence stack, achieved R, and one lesson — same habit, zero real money",
          "Only journal real-money trades",
          "Screenshot wins for social media",
        ],
        correctIndex: 1,
        explanation: "The simulator is a journaling gym: full trade cycles, real decisions, no capital at risk. The habit you build here is the one you'll rely on live.",
      },
      {
        type: "teach",
        text: "Takeaway: journal every trade with setup, R, adherence, and state. Review monthly, grouped by setup and by state. Judge yourself on process; let the data — not memory or mood — decide what changes.",
      },
    ],
  },

  trading_plan: {
    title: "Building a trading plan",
    steps: [
      {
        type: "teach",
        text: "A trading plan is your strategy written precisely enough that a stranger could execute it. It closes the gap where discretion becomes impulse. Core sections: (1) markets & sessions traded, (2) setups with exact entry criteria, (3) risk rules, (4) exit rules, (5) daily/weekly loss limits, (6) review schedule.",
      },
      {
        type: "question",
        prompt: "Which entry rule belongs in a real plan?",
        image: "plan-loop",
        options: [
          "'Buy when it looks strong'",
          "'Long only if: daily uptrend (HH/HL) + pullback into a fresh demand zone + sweep-and-reclaim trigger + achievable R:R ≥ 2'",
          "'Trade whatever's trending on social media'",
          "'Enter when bored'",
        ],
        correctIndex: 1,
        explanation: "Testable, checkable, binary. If a rule can't be answered YES/NO from the chart, it isn't a rule — it's a mood.",
      },
      {
        type: "question",
        prompt: "Why does a DAILY loss limit (e.g. stop trading at -2R on the day) exist separately from per-trade risk?",
        image: "expectancy-bars",
        options: [
          "Bureaucracy",
          "It caps the tilt cascade — the well-documented pattern where losses degrade decision quality and each next trade gets worse",
          "To reduce commissions only",
          "Daily limits increase risk",
        ],
        correctIndex: 1,
        explanation: "Per-trade risk protects the account from the market; the daily stop protects it from a compromised YOU. After consecutive losses, the best trade is usually the one not taken.",
      },
      {
        type: "teach",
        text: "PLANS CHANGE BY EVIDENCE, NOT EMOTION: rule changes happen at scheduled reviews, based on journal data (Unit 5, lesson 1), with one change at a time — otherwise you can't tell which change did what. Mid-session rule edits are tilt wearing a lab coat.",
      },
      {
        type: "question",
        prompt: "Wednesday, mid-session, two losses in: you feel your R:R minimum is 'too strict' and want to lower it right now. Per the plan discipline?",
        image: "expectancy-bars",
        options: [
          "Change it immediately — flexibility!",
          "Note the idea in the journal; evaluate it at the scheduled review against the data; change nothing mid-session",
          "Delete all rules in protest",
          "Ask social media to vote",
        ],
        correctIndex: 1,
        explanation: "Every mid-session rule change in history was 'obviously right' at the time. The review ritual exists precisely because in-the-moment you is the least qualified editor of the rules.",
      },
      {
        type: "question",
        prompt: "TRAP: after 15 losing trades over three weeks, a trader scraps the entire plan and adopts a new strategy — for the fourth time this quarter. What can they now measure?",
        image: "plan-loop",
        options: [
          "Everything, perfectly",
          "Nothing — no strategy ever got enough trades for its expectancy to emerge from variance; they've been sampling noise repeatedly",
          "All four strategies simultaneously",
          "The best of all worlds",
        ],
        correctIndex: 1,
        explanation: "15 trades of a 45%-win system quite normally contains ugly streaks. Strategy-hopping resets the sample every time, guaranteeing permanent statistical blindness. Edges need sample sizes.",
      },
      {
        type: "question",
        prompt: "Roughly how many trades of a setup do you need before its expectancy estimate deserves ANY confidence?",
        image: "trend-structure",
        options: [
          "3–5",
          "Dozens at minimum — variance dominates small samples; 30–50+ per setup is a reasonable floor before drawing conclusions",
          "One good one",
          "A million, so never bother",
        ],
        correctIndex: 1,
        explanation: "Exact thresholds vary, but single-digit samples are pure noise. This is why plans commit to a fixed evaluation period BEFORE judging — and why the simulator is valuable: samples are cheap here.",
      },
      {
        type: "question",
        prompt: "Which is the correct relationship between plan, journal, and review?",
        image: "plan-loop",
        options: [
          "They're three unrelated chores",
          "Plan defines the rules → journal records execution and outcomes → review compares them and evolves the plan — a closed improvement loop",
          "Journal replaces the plan",
          "Review happens only after blowing up",
        ],
        correctIndex: 1,
        explanation: "This loop IS the skill of trading as a practice: define, execute, measure, refine. Everything in this course feeds one of its three stages.",
      },
      {
        type: "teach",
        text: "Takeaway: write rules a stranger could follow, cap the damage a bad day can do, change rules only at reviews with data, and give every setup a real sample before judging it. The plan is the product; trades are just its output.",
      },
    ],
  },

  psychology_discipline: {
    title: "Trading psychology",
    steps: [
      {
        type: "teach",
        text: "Markets pay out on probabilities, but your brain evolved for certainty and threat. The predictable failure modes — revenge trading, loss aversion, FOMO, overconfidence after wins — aren't character flaws; they're default wiring. The job isn't to feel nothing; it's to build systems that keep default wiring away from the order button.",
      },
      {
        type: "question",
        prompt: "After a stop-out, you feel a hot urge to re-enter immediately at bigger size to 'get it back'. Name the pattern and the system-level defense.",
        image: "tilt-spiral",
        options: [
          "Intuition; obey it",
          "Revenge trading; defenses like a mandatory cooldown after any stop-out and the daily loss limit exist precisely for this moment",
          "Efficiency; faster is better",
          "It has no name",
        ],
        correctIndex: 1,
        explanation: "The urge itself is normal — acting on it is optional. Pre-committed rules (cooldowns, daily stops) work because they were written by calm-you and don't renegotiate with tilted-you.",
      },
      {
        type: "teach",
        text: "LOSS AVERSION: losses hurt roughly twice as much as equal gains feel good. Untreated, it produces the classic retail signature — snatching winners early ('lock it in!') and letting losers run ('it'll come back') — the exact inverse of positive expectancy.",
      },
      {
        type: "question",
        prompt: "Your journal shows avg win +0.6R against planned +2R targets, while losses reliably hit the full -1R. What's happening and what's the structural fix?",
        image: "downtrend-structure",
        options: [
          "Perfect trading",
          "Loss-aversion exits: winners cut at the first wobble. Fixes are structural — predefined targets, scaling rules, or moving stops only per written criteria, not per anxiety",
          "Targets are too small",
          "Add more indicators",
        ],
        correctIndex: 1,
        explanation: "The math from Unit 4: winners at +0.6R with 45% win rate is a losing system; the SAME entries with managed +2R winners is a solid edge. Exit discipline IS the edge for many traders.",
      },
      {
        type: "question",
        prompt: "FOMO check: a stock is up 30% today and everywhere on social media. You have no setup, no level, no plan — just the fear of missing it. The professional read?",
        image: "plan-loop",
        options: [
          "Buy first, think later — it's running!",
          "No setup = no trade; chasing vertical moves means entering where late buyers get trapped, with no definable invalidation",
          "Sell your house for size",
          "FOMO is a confluence factor",
        ],
        correctIndex: 1,
        explanation: "The pain of missing a move is real but costs nothing; the losses from chasing without invalidation are real and cost plenty. There is ALWAYS another trade — scarcity is the illusion FOMO sells.",
      },
      {
        type: "question",
        prompt: "TRAP: after 8 straight winners, a trader concludes they've 'figured it out', triples risk per trade, and loosens their entry criteria. What's operating?",
        image: "expectancy-bars",
        options: [
          "Earned mastery",
          "Overconfidence after a hot streak — variance being misread as skill, at the precise moment bigger risk meets sloppier entries",
          "Nothing risky at all",
          "The market owes them now",
        ],
        correctIndex: 1,
        explanation: "Hot streaks are exactly when discipline pays most: streaks end, and tripled risk plus loosened criteria converts a normal cold patch into a crater. Rules apply hardest when you feel invincible.",
      },
      {
        type: "question",
        prompt: "Which reframe makes a rule-following -1R loss easier to take — and is also TRUE?",
        image: "downtrend-structure",
        options: [
          "'I failed and should feel bad'",
          "'That's one paid installment of variance in a positive-expectancy process — the cost of doing business, logged and done'",
          "'The market cheated'",
          "'Losses mean the system is broken'",
        ],
        correctIndex: 1,
        explanation: "A 45%-win system DELIVERS 55 losses per hundred trades as a feature of its profitability. Internalizing that turns losses from identity-threats into line items — which is what keeps process intact.",
      },
      {
        type: "question",
        prompt: "State management: which pre-session check is actually load-bearing rather than ritual?",
        image: "downtrend-structure",
        options: [
          "Lucky socks",
          "A honest go/no-go: slept? calm? not chasing yesterday? If no — reduce size or don't trade; your state is part of the system",
          "Reading price predictions",
          "None — grind through everything",
        ],
        correctIndex: 1,
        explanation: "The journal evidence from Unit 5 lesson 1 (tilted trades ≈ -0.8R) makes this concrete: trading impaired has a measurable cost. Declining to trade is a position too — often the best-paying one.",
      },
      {
        type: "question",
        prompt: "Final integration: where does psychology actually live in everything you've built across this course?",
        image: "downtrend-structure",
        options: [
          "In motivational quotes",
          "Inside the structures: sizing that survives streaks, plans a stranger could follow, journals that override memory, limits that fire before tilt does — discipline is engineered, not summoned",
          "In willpower alone, summoned fresh each trade",
          "Nowhere — psychology is a myth",
        ],
        correctIndex: 1,
        explanation: "You will not out-willpower your wiring in the moment. Every unit of this course quietly built the cage around it: costs → sizing → structure → evidence → process. That cage is the skill.",
      },
      {
        type: "teach",
        text: "Takeaway: expect the urges — revenge, loss aversion, FOMO, overconfidence — and defeat them in advance with structure: cooldowns, loss limits, written exits, honest pre-session checks. Process over outcome, every single day. That's the whole game.",
      },
    ],
  },

  advanced_confluence: {
    title: "Confluence: stacking your edge",
    steps: [
      {
        type: "teach",
        text: "Confluence = multiple INDEPENDENT pieces of evidence pointing the same way at the same place. Independent is the key word: structure, level/zone, liquidity event, momentum, volume, higher-timeframe context — different kinds of evidence, not six restatements of one.",
      },
      {
        type: "question",
        prompt: "Which pair is genuinely INDEPENDENT confluence?",
        image: "confluence-stack",
        options: [
          "RSI(14) oversold + RSI(7) oversold",
          "A fresh daily demand zone + a liquidity sweep of the low just in front of it",
          "Two moving averages of similar length both rising",
          "The same trendline drawn twice",
        ],
        correctIndex: 1,
        explanation: "A zone (order concentration) and a sweep (stop-harvest event) are different mechanisms agreeing. Two similar indicators are one signal wearing two hats — remember the indicator-stacking trap.",
      },
      {
        type: "question",
        prompt: "Score these two longs. A: uptrend + pullback to fresh demand + sweep of a minor low + 3:1 achievable R:R. B: 'RSI is low'. What separates them?",
        image: "liquidity-sweep",
        options: [
          "Nothing — both are fine",
          "A stacks independent evidence with defined invalidation; B is a single derivative reading with no structure behind it",
          "B is better — simpler",
          "Letter A is luckier",
        ],
        correctIndex: 1,
        explanation: "A is a thesis: WHERE (zone), WHY NOW (sweep), WITH WHAT (trend), WORTH WHAT (R:R). B is a number on an oscillator. Confluence is the difference between a trade idea and an impulse.",
      },
      {
        type: "teach",
        text: "A practical filter: require a minimum evidence stack before risking — e.g. trend alignment + a level/zone + a trigger (reaction, sweep-reclaim, structure shift on entry timeframe) + acceptable R:R. No stack, no trade. Boredom is part of the job.",
      },
      {
        type: "question",
        prompt: "Price is mid-range, far from any level, no trend, no trigger — but you're bored and 'feel' it's going up. Per the filter?",
        image: "range-vs-trend",
        options: [
          "Small punt is harmless",
          "No stack, no trade — this is exactly the impulse the filter exists to block",
          "Double size to make boredom pay",
          "Feelings are a confluence factor",
        ],
        correctIndex: 1,
        explanation: "Most losing trades aren't bad setups — they're NON-setups taken out of boredom. The filter's biggest job is generating NO more often than GO.",
      },
      {
        type: "question",
        prompt: "TRAP: after deciding you want to be long, you find five reasons supporting it and dismiss three warnings. What's happening?",
        image: "sr-zone",
        options: [
          "Excellent research",
          "Confirmation bias dressed as confluence — evidence gathered AFTER the conclusion isn't independent of your desire",
          "The warnings prove it's a buy",
          "Five beats three, case closed",
        ],
        correctIndex: 1,
        explanation: "Real confluence is usually visible BEFORE you want the trade — it creates the desire, not the reverse. If you're lawyering for a position, you're rationalizing. The tell: genuine setups rarely need persuading.",
      },
      {
        type: "question",
        prompt: "Confluence also applies to EXITS. Your long approaches: prior swing high + a fresh supply zone + your 2.5R target, all within the same band. What is that band?",
        image: "downtrend-structure",
        options: [
          "A reason to add size",
          "A logical take-profit area — multiple reasons for sellers to appear are stacked there",
          "Meaningless overlap",
          "A place to move stops further away",
        ],
        correctIndex: 1,
        explanation: "The same stacking logic that finds entries finds exits: where independent evidence says opposition gathers, that's where you pay yourself rather than hope through it.",
      },
      {
        type: "question",
        prompt: "Does more confluence mean bigger position size?",
        image: "stop-bracket",
        options: [
          "Yes — 10x size on 'perfect' setups",
          "Risk stays within your fixed per-trade limit; confluence selects WHICH trades to take, it doesn't suspend sizing rules",
          "Confluence removes the need for stops",
          "Size is random anyway",
        ],
        correctIndex: 1,
        explanation: "Even A+ setups fail routinely. Some traders vary risk modestly within a capped band (e.g. 0.5%–1%), but confluence never licenses risk that a losing streak couldn't survive.",
      },
      {
        type: "teach",
        text: "Takeaway: demand a stack of independent evidence — context, location, trigger, payoff — before risking anything. Let confluence pick trades and mark exits, while sizing rules stay untouched. And when the stack isn't there, the trade is NO.",
      },
    ],
  },
};
